package com.example.myapp.game

enum class ObjectiveType {
    SURVIVE_WAVES,
    PERFECT_BASE,        // 0 base damage taken
    BASE_HP_ABOVE,       // Base HP >= targetValue% (e.g. 80)
    NO_TOWERS_SOLD,      // No towers sold
    MAX_TOWERS_PLACED,   // Total towers placed <= targetValue
    FORBIDDEN_TOWER,     // Never placed forbiddenTower
    NO_POWERS_USED,      // powersUsed == 0
    MIN_COMBO,           // bestCombo >= targetValue
    HERO_SLAYS_BOSS      // Hero delivered fatal damage to a boss
}

data class CampaignObjective(
    val type: ObjectiveType,
    val targetValue: Int = 0,
    val forbiddenTower: TowerType? = null,
    val descEn: String,
    val descPl: String
) {
    fun description(isPl: Boolean): String = if (isPl) descPl else descEn
}

data class CampaignLevel(
    val id: Int,
    val title: String,
    val description: String,
    val emoji: String,
    val targetWave: Int,
    val startingGold: Int = 50,
    val allowedTowers: Set<TowerType> = TowerType.entries.toSet(),
    val allowedPowers: Set<PowerType> = PowerType.entries.toSet(),
    val upgradesEnabled: Boolean = true,
    val enemyHpMult: Float = 1f,
    val enemyDmgMult: Float = 1f,
    val enemySpeedMult: Float = 1f,
    val goldMult: Float = 1f,
    val spawnRateMult: Float = 1f,
    val diamondReward: Int = 3,
    val hint: String = "",
    val mapType: MapType = MapType.CLASSIC,
    val objective1: CampaignObjective = CampaignObjective(
        ObjectiveType.SURVIVE_WAVES,
        targetWave,
        null,
        "Clear all $targetWave waves",
        "Przetrwaj wszystkie $targetWave fale"
    ),
    val objective2: CampaignObjective = CampaignObjective(
        ObjectiveType.PERFECT_BASE,
        0,
        null,
        "Flawless Citadel (0 Base Damage)",
        "Nienaruszona Cytadela (0 obrażeń bazy)"
    ),
    val objective3: CampaignObjective = CampaignObjective(
        ObjectiveType.NO_TOWERS_SOLD,
        0,
        null,
        "Tactical Discipline (No towers sold)",
        "Dyscyplina Taktyczna (Bez sprzedaży wież)"
    )
) {
    /** Estimate the base score (gold from kills without combos) for this level. */
    private fun estimatedBaseScore(): Int {
        var total = 0f
        val bossInterval = 5
        for (w in 1..targetWave) {
            val waveScale = 1f + (w - 1) * 0.15f
            if (w % bossInterval == 0) {
                // Boss gold + ~5 minions
                val bossGold = (50f + w * 10f) * waveScale * goldMult
                val minionGold = 5 * 5f * waveScale * goldMult
                total += bossGold + minionGold
            } else {
                val count = ((3 + w * 2) * spawnRateMult).toInt()
                val avgGold = 5f + w * 0.8f
                total += count * avgGold * waveScale * goldMult
            }
        }
        return total.toInt()
    }

    /** Score needed for 2 stars — requires decent play with some combo chaining. */
    val star2Score: Int get() = (estimatedBaseScore() * 0.8f).toInt().coerceAtLeast(50)

    /** Score needed for 3 stars — requires sustained high combos and efficient kills. */
    val star3Score: Int get() = (estimatedBaseScore() * 1.5f).toInt().coerceAtLeast(100)
}

object CampaignData {

    val levels = listOf(
        CampaignLevel(
            id = 1,
            title = "The Basics",
            description = "Learn the fundamentals: place Arrow towers along the path to halt the goblin advance.",
            emoji = "\uD83C\uDFF9",
            targetWave = 3,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.6f,
            enemyDmgMult = 0.5f,
            enemySpeedMult = 0.8f,
            goldMult = 1.5f,
            diamondReward = 3,
            hint = "Tap the Arrow tower, then tap an empty spot near the path to build.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 3, null, "Clear all 3 waves", "Przetrwaj wszystkie 3 fale"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Defense (0 damage)", "Bezb\u0142\u0119dna obrona (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 3, null, "Build at most 3 towers", "Postaw maksymalnie 3 wie\u017ce")
        ),
        CampaignLevel(
            id = 2,
            title = "Arcane Penetration",
            description = "Armored orcs resist physical arrows \u2014 introduce Magic towers to pierce their defenses.",
            emoji = "\uD83E\uDDE8",
            targetWave = 4,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.7f,
            enemyDmgMult = 0.6f,
            enemySpeedMult = 0.85f,
            goldMult = 1.3f,
            diamondReward = 3,
            hint = "Magic attacks ignore heavy armor; mix Arrow and Magic towers along the bends.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 4, null, "Clear all 4 waves", "Przetrwaj wszystkie 4 fale"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Protect the Citadel (0 damage)", "Chro\u0144 Cytadel\u0119 (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Tactical Discipline (No sales)", "Dyscyplina (Bez sprzeda\u017cy)")
        ),
        CampaignLevel(
            id = 3,
            title = "Explosive Impact",
            description = "Swarming packs of goblins incoming! Deploy Cannon towers to blast clustered groups.",
            emoji = "\uD83D\uDCA3",
            targetWave = 5,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.8f,
            enemyDmgMult = 0.7f,
            enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Cannons deal area splash damage \u2014 position them at intersection curves where enemies bunch up.",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 5, null, "Clear all 5 waves", "Przetrwaj wszystkie 5 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 15, null, "Achieve 15x Kill Combo", "Osi\u0105gnij combo 15x"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 5, null, "Construct at most 5 towers", "Postaw maksymalnie 5 wie\u017c")
        ),
        CampaignLevel(
            id = 4,
            title = "Field Engineering",
            description = "Upgrade systems online! Enhance tower range, attack speed, and hero combat prowess.",
            emoji = "\u2B06\uFE0F",
            targetWave = 5,
            startingGold = 110,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f,
            enemyDmgMult = 0.8f,
            enemySpeedMult = 0.95f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Tap a built tower to upgrade it. Upgraded towers gain massive power and range.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 5, null, "Clear Wave 5", "Przetrwaj Fal\u0119 5"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 5,
            title = "First Blood",
            description = "The Goblin Chieftain emerges! Dodge telegraphed boss strikes and take him down.",
            emoji = "\u2620\uFE0F",
            targetWave = 5,
            startingGold = 130,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.95f,
            enemyDmgMult = 0.85f,
            enemySpeedMult = 1.0f,
            goldMult = 1.2f,
            diamondReward = 5,
            hint = "Watch the glowing red warning circle under the boss and move the hero away before the stomp!",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 5, null, "Defeat the Goblin Chieftain", "Pokonaj Wodza Goblin\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes final boss blow", "Bohater zadaje ostateczny cios"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base Defense", "Nienaruszona baza")
        ),
        CampaignLevel(
            id = 6,
            title = "Chill Factor",
            description = "Fast wolf riders sprint past defenses! Deploy Ice towers and cast the Freeze spell.",
            emoji = "\u2744\uFE0F",
            targetWave = 6,
            startingGold = 140,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.ICE),
            allowedPowers = setOf(PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 0.85f,
            enemyDmgMult = 0.85f,
            enemySpeedMult = 1.3f,
            goldMult = 1.1f,
            diamondReward = 5,
            hint = "Ice towers slow whole lanes, keeping fast enemies in cannon crossfire.",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 6, null, "Clear all 6 waves", "Przetrwaj wszystkie 6 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 20, null, "Achieve 20x Kill Combo", "Osi\u0105gnij combo 20x"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 7,
            title = "Fire & Fury",
            description = "Regenerating forest trolls! Unleash Flame towers and drop catastrophic Fireballs.",
            emoji = "\uD83D\uDD25",
            targetWave = 7,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.ICE, TowerType.FLAME),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL),
            upgradesEnabled = true,
            enemyHpMult = 1.0f,
            enemyDmgMult = 0.9f,
            enemySpeedMult = 0.95f,
            goldMult = 1.1f,
            diamondReward = 5,
            hint = "Flame towers burn continuous cones of fire; Fireball obliterates enemy choke points.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 7, null, "Clear Wave 7", "Przetrwaj Fal\u0119 7"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers built", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel", "Czysta baza")
        ),
        CampaignLevel(
            id = 8,
            title = "Static Discharge",
            description = "Armored iron golems approaching in tight formation. Deploy Tesla towers and chain Lightning.",
            emoji = "\u26A1",
            targetWave = 7,
            startingGold = 160,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.ICE, TowerType.FLAME, TowerType.TESLA),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL, PowerType.LIGHTNING),
            upgradesEnabled = true,
            enemyHpMult = 1.05f,
            enemyDmgMult = 0.95f,
            enemySpeedMult = 1.0f,
            goldMult = 1.1f,
            diamondReward = 6,
            hint = "Tesla attacks arc between multiple nearby enemies, shredding metal armor.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 7, null, "Clear all 7 waves", "Przetrwaj wszystkie 7 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 25, null, "Achieve 25x Kill Combo", "Osi\u0105gnij combo 25x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Tactical Discipline (No sales)", "Dyscyplina (Bez sprzeda\u017cy)")
        ),
        CampaignLevel(
            id = 9,
            title = "Venomous Trail",
            description = "High-HP beast packs require sustained attrition. Lay down Poison towers to rot them as they march.",
            emoji = "\u2623\uFE0F",
            targetWave = 8,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.ICE, TowerType.FLAME, TowerType.TESLA, TowerType.POISON),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL, PowerType.LIGHTNING),
            upgradesEnabled = true,
            enemyHpMult = 1.15f,
            enemyDmgMult = 1.0f,
            enemySpeedMult = 0.95f,
            goldMult = 1.1f,
            diamondReward = 6,
            hint = "Poison damage stacks and continues hurting enemies long after they pass the tower.",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Clear all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 7, null, "Max 7 towers placed", "Maksymalnie 7 wie\u017c")
        ),
        CampaignLevel(
            id = 10,
            title = "Garrison Commander",
            description = "Act 1 Finale! The Ogre General commands 8 brutal waves of combined arms forces.",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 8,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.ICE, TowerType.FLAME, TowerType.TESLA, TowerType.POISON),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL, PowerType.LIGHTNING),
            upgradesEnabled = true,
            enemyHpMult = 1.2f,
            enemyDmgMult = 1.1f,
            enemySpeedMult = 1.0f,
            goldMult = 1.15f,
            diamondReward = 8,
            hint = "Combine slow (Ice), attrition (Poison/Flame), and burst (Cannon/Tesla) to hold the line.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Vanquish the Ogre General", "Zg\u0142ad\u017a Genera\u0142a Ogr\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero delivers boss death strike", "Bohater dobija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Victory (0 damage)", "Bezb\u0142\u0119dne zwyci\u0119stwo (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 11,
            title = "Siege Ballistics",
            description = "Massive armored juggernauts approach from extreme range. Build Ballista sniper towers.",
            emoji = "\uD83C\uDFAF",
            targetWave = 8,
            startingGold = 160,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON, TowerType.BALLISTA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.1f,
            enemySpeedMult = 0.85f,
            goldMult = 1.1f,
            diamondReward = 6,
            hint = "Ballista has immense range and heavy single-target punch; position them far back.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.CANNON, "No Cannon towers", "Bez armat"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 12,
            title = "Soul Harvester",
            description = "Harness the dark arts! Necromancer towers siphon souls of slain enemies into bolts of dread.",
            emoji = "\uD83D\uDC80",
            targetWave = 9,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.POISON, TowerType.NECRO),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.15f,
            enemyDmgMult = 1.05f,
            enemySpeedMult = 1.05f,
            goldMult = 1.15f,
            diamondReward = 7,
            hint = "Necro towers gain increased attack potency with high nearby kill density.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Clear Wave 9", "Przetrwaj Fal\u0119 9"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 30, null, "Achieve 30x Kill Combo", "Osi\u0105gnij combo 30x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Tactical Discipline", "Dyscyplina taktyczna")
        ),
        CampaignLevel(
            id = 13,
            title = "Gravitational Pull",
            description = "Vortex towers warp gravity, pulling marching foes together into devastating kill zones.",
            emoji = "\uD83C\uDF00",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.TESLA, TowerType.VORTEX),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f,
            enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f,
            goldMult = 1.1f,
            diamondReward = 7,
            hint = "Place Vortex towers right next to Cannons and Teslas so pulled enemies take maximum splash.",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 6, null, "Max 6 towers placed", "Maksymalnie 6 wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 14,
            title = "Field Medic",
            description = "Enemies attack with siege poison! Build Healer towers and cast the Heal spell to sustain the base.",
            emoji = "\uD83D\uDC9A",
            targetWave = 10,
            startingGold = 170,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.BALLISTA, TowerType.HEALER),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f,
            enemyDmgMult = 1.25f,
            enemySpeedMult = 1.0f,
            goldMult = 1.1f,
            diamondReward = 7,
            hint = "Healer towers restore base HP and mend the hero in combat when nearby.",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 95, null, "Base HP \u2265 95%", "Zdrowie bazy \u2265 95%"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 15,
            title = "The Grand Arsenal",
            description = "All 11 tower types are now fully unlocked! Unleash your ideal defensive synergy.",
            emoji = "\uD83D\uDD13",
            targetWave = 10,
            startingGold = 200,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.15f,
            enemySpeedMult = 1.05f,
            goldMult = 1.1f,
            diamondReward = 8,
            hint = "Combine any towers you like: Ice slow + Flame burn + Vortex pull + Ballista snipes.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 16,
            title = "Night Patrol",
            description = "Thick fog and darkness shroud the road \u2014 enemy health is heightened and range is tested.",
            emoji = "\uD83C\uDF19",
            targetWave = 9,
            startingGold = 150,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f,
            enemyDmgMult = 1.15f,
            enemySpeedMult = 1.0f,
            goldMult = 1.15f,
            diamondReward = 7,
            hint = "Build towers close to the roads and upgrade tower range to counter the night.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Clear Wave 9", "Przetrwaj Fal\u0119 9"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Night (0 damage)", "Bezb\u0142\u0119dna noc (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 7, null, "Max 7 towers placed", "Maksymalnie 7 wie\u017c")
        ),
        CampaignLevel(
            id = 17,
            title = "Ironclad Vanguard",
            description = "Heavy armor division! Physical weapons clatter harmlessly \u2014 magic and lightning are paramount.",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 170,
            allowedTowers = TowerType.entries.filter { it != TowerType.ARROW && it != TowerType.BALLISTA }.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f,
            enemyDmgMult = 1.2f,
            enemySpeedMult = 0.85f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Magic, Tesla, and Flame melt through the armored plating of the vanguard.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 18,
            title = "Sprinters' Ambush",
            description = "Hyper-speed cavalry swarms! Rapid reaction and deep freezing required.",
            emoji = "\uD83C\uDFC7",
            targetWave = 10,
            startingGold = 160,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.85f,
            enemyDmgMult = 1.0f,
            enemySpeedMult = 1.55f,
            goldMult = 1.15f,
            diamondReward = 8,
            hint = "Place multiple Ice towers along the path to keep sprinters permanently slowed.",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Kill Combo", "Osi\u0105gnij combo 40x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Defense (0 damage)", "Bezb\u0142\u0119dna obrona (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 19,
            title = "Sealed Incantations",
            description = "An anti-magic storm suppresses your spellbook \u2014 win purely with tower tactics and hero steel.",
            emoji = "\uD83D\uDD12",
            targetWave = 10,
            startingGold = 210,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.15f,
            enemySpeedMult = 1.0f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Without spells, rely on upgraded choke points and active hero positioning.",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Survive all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells cast", "Bez rzucania czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 20,
            title = "Warlord's Rampage",
            description = "Act 2 Finale! The Armored Warlord assaults the caldera with twin war-beasts.",
            emoji = "\uD83D\uDC79",
            targetWave = 12,
            startingGold = 220,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.35f,
            enemyDmgMult = 1.25f,
            enemySpeedMult = 1.05f,
            goldMult = 1.2f,
            diamondReward = 10,
            hint = "Boss at wave 6 and final Warlord at wave 12 \u2014 save hero abilities for phase breaks.",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Slay the Armored Warlord", "Zg\u0142ad\u017a Opancerzonego Wodza"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero slays the Warlord", "Bohater zabija Wodza"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 21,
            title = "Thermal Shatter",
            description = "Sub-zero blizzard terrain! Pair Flame and Ice towers to trigger thermal explosions.",
            emoji = "\u2744\uFE0F\uD83D\uDD25",
            targetWave = 10,
            startingGold = 190,
            allowedTowers = setOf(TowerType.ARROW, TowerType.ICE, TowerType.FLAME, TowerType.BALLISTA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.15f,
            enemySpeedMult = 1.1f,
            goldMult = 1.1f,
            diamondReward = 8,
            hint = "Ice slows targets while Flame incinerates them for maximum elemental reaction.",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 30, null, "Achieve 30x Kill Combo", "Osi\u0105gnij combo 30x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 22,
            title = "Plague & Shadows",
            description = "Cursed swamp! Synergize Poison towers with Necromancers to melt swarms.",
            emoji = "\u2620\uFE0F",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.MAGIC, TowerType.POISON, TowerType.NECRO, TowerType.TESLA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f,
            enemyDmgMult = 1.2f,
            enemySpeedMult = 1.0f,
            goldMult = 1.15f,
            diamondReward = 8,
            hint = "Stack poison ticks, then let Necromancers harvest every fallen soul.",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 23,
            title = "Arcane Overload",
            description = "Overcharge the crossroads with Magic and Tesla batteries for lethal chain storms.",
            emoji = "\u26A1\u2728",
            targetWave = 11,
            startingGold = 200,
            allowedTowers = setOf(TowerType.MAGIC, TowerType.TESLA, TowerType.VORTEX, TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f,
            enemyDmgMult = 1.2f,
            enemySpeedMult = 1.05f,
            goldMult = 1.1f,
            diamondReward = 9,
            hint = "Vortex pulls enemies together, allowing Tesla lightning to bounce between everyone.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear Wave 11", "Przetrwaj Fal\u0119 11"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 6, null, "Max 6 towers placed", "Maksymalnie 6 wie\u017c")
        ),
        CampaignLevel(
            id = 24,
            title = "Gold Drought",
            description = "Severe supply embargo \u2014 gold is strictly rationed! Upgrade carefully.",
            emoji = "\uD83D\uDCB0",
            targetWave = 9,
            startingGold = 40,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f,
            enemyDmgMult = 1.0f,
            enemySpeedMult = 1.0f,
            goldMult = 0.7f,
            diamondReward = 8,
            hint = "Place 2 high-value towers and upgrade them rather than building many weak ones.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Survive with low gold", "Przetrwaj z ma\u0142ym z\u0142otem"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 25,
            title = "Glass Bastion",
            description = "Base integrity compromised! Base HP capped at 50 \u2014 zero tolerance for breaches.",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 240,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.15f,
            enemyDmgMult = 1.1f,
            enemySpeedMult = 1.05f,
            goldMult = 1.2f,
            diamondReward = 9,
            hint = "Even 2-3 leaks will destroy the base. Place slow and stun towers at choke points.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 26,
            title = "Thunderstrike Ridge",
            description = "Severe thunderstorm roars across the peak! Lightning powers recharge faster.",
            emoji = "\uD83C\uDF29\uFE0F",
            targetWave = 11,
            startingGold = 210,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.35f,
            enemyDmgMult = 1.2f,
            enemySpeedMult = 1.1f,
            goldMult = 1.15f,
            diamondReward = 9,
            hint = "Take advantage of storm weather; chain lightning deals double impact on soaked targets.",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear all 11 waves", "Przetrwaj wszystkie 11 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Kill Combo", "Osi\u0105gnij combo 40x"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 27,
            title = "The Vermin Swarm",
            description = "Triple enemy count with reduced health! Clustered waves test your AoE mastery.",
            emoji = "\uD83D\uDC00",
            targetWave = 11,
            startingGold = 190,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.5f,
            enemyDmgMult = 0.7f,
            enemySpeedMult = 1.25f,
            goldMult = 1.1f,
            spawnRateMult = 2.2f,
            diamondReward = 9,
            hint = "Cannons, Flame cones, and Teslas will rack up enormous combos against swarms.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear Wave 11", "Przetrwaj Fal\u0119 11"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 60, null, "Achieve 60x Swarm Combo", "Osi\u0105gnij combo 60x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Defense (0 damage)", "Bezb\u0142\u0119dna obrona (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 28,
            title = "No Upgrades Protocol",
            description = "Tower and Hero upgrade mechanics disabled \u2014 victory depends solely on strategic layout.",
            emoji = "\uD83D\uDEAB",
            targetWave = 10,
            startingGold = 280,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = false,
            enemyHpMult = 1.05f,
            enemyDmgMult = 1.0f,
            enemySpeedMult = 1.0f,
            goldMult = 1.2f,
            diamondReward = 9,
            hint = "Spread diverse base towers across the entire map to cover all angles.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 29,
            title = "Champion's Duty",
            description = "Towers deal reduced damage \u2014 your Hero must spearhead the combat line.",
            emoji = "\u2694\uFE0F",
            targetWave = 12,
            startingGold = 170,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f,
            enemyDmgMult = 1.1f,
            enemySpeedMult = 1.0f,
            goldMult = 1.25f,
            diamondReward = 10,
            hint = "Micro your hero into the vanguard; bait boss attacks away from towers.",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater zabija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 7, null, "Max 7 towers placed", "Maksymalnie 7 wie\u017c")
        ),
        CampaignLevel(
            id = 30,
            title = "Draconic Caldera",
            description = "Act 3 Climax! The Ancient Red Dragon descends upon the volcano crater.",
            emoji = "\uD83D\uDC09",
            targetWave = 15,
            startingGold = 250,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f,
            enemyDmgMult = 1.3f,
            enemySpeedMult = 1.1f,
            goldMult = 1.25f,
            diamondReward = 12,
            hint = "The dragon casts flame sweeps at wave 10 and 15 \u2014 build deep Ballista sniper defense.",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Slay the Ancient Dragon", "Zg\u0142ad\u017a Staro\u017cytnego Smoka"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero delivers death blow", "Bohater zadaje \u015bmiertelny cios"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 31,
            title = "Trench Warfare",
            description = "Narrow winding trenches \u2014 funnel enemies into concentrated kill-zones.",
            emoji = "\uD83E\uDE96",
            targetWave = 12,
            startingGold = 200,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f,
            enemyDmgMult = 1.25f,
            enemySpeedMult = 1.1f,
            goldMult = 1.15f,
            diamondReward = 10,
            hint = "Use the winding terrain to overlap Cannon splash and Poison pools.",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 45, null, "Achieve 45x Kill Combo", "Osi\u0105gnij combo 45x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 32,
            title = "Sub-Zero Glaciation",
            description = "Freezing blizzard slows both allies and foes. Fortify the icy narrows.",
            emoji = "\uD83E\uDD76",
            targetWave = 12,
            startingGold = 210,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.45f,
            enemyDmgMult = 1.3f,
            enemySpeedMult = 1.15f,
            goldMult = 1.2f,
            diamondReward = 10,
            hint = "Enemies have thick ice armor; rely on Tesla electric arcs and Flame towers.",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%"),
            objective3 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych")
        ),
        CampaignLevel(
            id = 33,
            title = "Volcanic Fissures",
            description = "Periodic magma eruptions scorch sections of the road! Fast pyro-beasts invade.",
            emoji = "\uD83C\uDF0B",
            targetWave = 13,
            startingGold = 220,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.5f,
            enemyDmgMult = 1.35f,
            enemySpeedMult = 1.15f,
            goldMult = 1.2f,
            diamondReward = 11,
            hint = "Eruptions can clear enemies, but magma beasts speed up when near lava.",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 13, null, "Clear Wave 13", "Przetrwaj Fal\u0119 13"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Defense (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MIN_COMBO, 50, null, "Achieve 50x Kill Combo", "Osi\u0105gnij combo 50x")
        ),
        CampaignLevel(
            id = 34,
            title = "Arcane Null-Zone",
            description = "Magic towers and spells completely suppressed. Rely on siege ballistics and traps.",
            emoji = "\uD83D\uDEAB\u2728",
            targetWave = 12,
            startingGold = 250,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.BALLISTA, TowerType.POISON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 1.35f,
            enemyDmgMult = 1.2f,
            enemySpeedMult = 1.1f,
            goldMult = 1.25f,
            diamondReward = 11,
            hint = "Without magic, physical ballistic volleys must carry the entire line.",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 8, null, "Max 8 towers placed", "Maksymalnie 8 wie\u017c")
        ),
        CampaignLevel(
            id = 35,
            title = "The Swarm Broodmother",
            description = "Toxic Broodmother spawns endless spiderlings upon taking damage.",
            emoji = "\uD83D\uDD77\uFE0F",
            targetWave = 14,
            startingGold = 230,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.55f,
            enemyDmgMult = 1.35f,
            enemySpeedMult = 1.15f,
            goldMult = 1.2f,
            spawnRateMult = 1.5f,
            diamondReward = 12,
            hint = "Focus burst fire on the Broodmother while splash weapons wipe the spiderling hatchlings.",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Slay the Broodmother", "Zg\u0142ad\u017a Matk\u0119 Roju"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 70, null, "Achieve 70x Kill Combo", "Osi\u0105gnij combo 70x"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 36,
            title = "Titan's Tremor",
            description = "Earth Titan stomps cause massive seismic waves that stun nearby towers.",
            emoji = "\uD83D\uDDFB",
            targetWave = 15,
            startingGold = 260,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.6f,
            enemyDmgMult = 1.4f,
            enemySpeedMult = 1.1f,
            goldMult = 1.2f,
            diamondReward = 13,
            hint = "Spread your towers apart so a single Titan Stomp doesn't stun your entire defensive grid.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Defeat Earth Titan", "Pokonaj Ziemskiego Tytana"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater dobija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 37,
            title = "Shadow Assassins",
            description = "Stealth shadow units sprint at maximum speed through defenses.",
            emoji = "\uD83D\uDC65",
            targetWave = 14,
            startingGold = 220,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f,
            enemyDmgMult = 1.3f,
            enemySpeedMult = 1.5f,
            goldMult = 1.2f,
            diamondReward = 12,
            hint = "Layer Ice towers with high-rate Tesla and Arrow towers to burst down sprinting shadows.",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Clear Wave 14", "Przetrwaj Fal\u0119 14"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "Zero Tower Sales", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 38,
            title = "Twin Calderas",
            description = "Two boss waves back-to-back: the Fire Lord and the Ice Wyrm simultaneously!",
            emoji = "\uD83C\uDF0B\u2744\uFE0F",
            targetWave = 16,
            startingGold = 280,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.65f,
            enemyDmgMult = 1.45f,
            enemySpeedMult = 1.15f,
            goldMult = 1.2f,
            diamondReward = 14,
            hint = "Balance physical and elemental towers to handle both opposite boss resistances.",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 16, null, "Clear all 16 waves", "Przetrwaj wszystkie 16 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 8, null, "Max 8 towers placed", "Maksymalnie 8 wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 39,
            title = "Cosmic Singularity",
            description = "Reality fractures as void rifts test every tool in your arsenal.",
            emoji = "\uD83C\uDF0C",
            targetWave = 18,
            startingGold = 300,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.7f,
            enemyDmgMult = 1.5f,
            enemySpeedMult = 1.2f,
            goldMult = 1.2f,
            diamondReward = 15,
            hint = "Use Vortex and Ballista synergies to snipe high-threat void callers from afar.",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 18, null, "Survive Void Incursion", "Przetrwaj Inwazj\u0119 Pustki"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 60, null, "Achieve 60x Kill Combo", "Osi\u0105gnij combo 60x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 40,
            title = "The Grand Champion",
            description = "The supreme trial of the classic campaign! 20 escalating waves culminating in the Warlord Titan.",
            emoji = "\uD83C\uDFC6",
            targetWave = 20,
            startingGold = 320,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.8f,
            enemyDmgMult = 1.6f,
            enemySpeedMult = 1.2f,
            goldMult = 1.2f,
            diamondReward = 20,
            hint = "Mastery of all 11 towers, spell timings, and hero dodging will decide this grand finale.",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 20, null, "Clear all 20 waves", "Przetrwaj wszystkie 20 fal"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Champion", "Bohater zabija Czempiona"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 41,
            title = "Thermal Shockwave",
            description = "Trigger Fire and Ice combinations to shatter magma beasts",
            emoji = "\uD83C\uDF0B",
            targetWave = 10,
            startingGold = 220,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            enemyHpMult = 1.2f,
            enemyDmgMult = 1.1f,
            diamondReward = 12,
            hint = "Pair Flame and Ice towers closely together to trigger thermal explosions",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 42,
            title = "The Red Gauntlet",
            description = "High-speed desert skirmish \u2014 rapid firing required",
            emoji = "\uD83C\uDFDC\uFE0F",
            targetWave = 8,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.TESLA),
            allowedPowers = setOf(PowerType.LIGHTNING),
            enemyHpMult = 0.75f,
            enemySpeedMult = 1.45f,
            diamondReward = 12,
            hint = "Place rapid-firing Arrow and Ballista towers with quick target acquisition",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 6, null, "Max 6 towers placed", "Maksymalnie 6 postawionych wie\u017c")
        ),
        CampaignLevel(
            id = 43,
            title = "Glass Citadel",
            description = "Base HP capped at 10! A single breach spells ruin",
            emoji = "\uD83C\uDFF0",
            targetWave = 12,
            startingGold = 400,
            allowedTowers = TowerType.entries.filter { it != TowerType.HEALER }.toSet(),
            goldMult = 1.5f,
            diamondReward = 14,
            hint = "High gold reserves \u2014 fortify both lanes so zero enemies pass through",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 44,
            title = "Lava Walkers",
            description = "Magma beasts immune to fire \u2014 rely on frost and arcane kinetic force",
            emoji = "\uD83E\uDD80",
            targetWave = 10,
            startingGold = 200,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.ICE, TowerType.TESLA, TowerType.BALLISTA),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.LIGHTNING),
            diamondReward = 13,
            hint = "Ice towers slow the magma beasts while Magic penetrates their molten shells",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.FLAME, "No Flame towers", "Bez wie\u017c ognia"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 45,
            title = "Molten Calamity",
            description = "Enraged Demon Prince assaults the caldera with seismic stomps",
            emoji = "\uD83D\uDE08",
            targetWave = 15,
            startingGold = 300,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.3f,
            diamondReward = 15,
            hint = "Watch for the 1.5s boss telegraph zone to move the hero out of danger",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Defeat the Demon Prince", "Pokonaj Ksi\u0119cia Demon\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater zabija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 46,
            title = "Ethereal Mist",
            description = "Spectral ghosts resist physical damage \u2014 harness the occult and electric",
            emoji = "\uD83C\uDF2B\uFE0F",
            targetWave = 9,
            startingGold = 210,
            allowedTowers = setOf(TowerType.MAGIC, TowerType.TESLA, TowerType.NECRO, TowerType.POISON),
            diamondReward = 13,
            hint = "Physical projectiles deal minimal damage; use Tesla and Magic arcs",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Clear Wave 9", "Przetrwaj Fal\u0119 9"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 47,
            title = "Duel in the Crypt",
            description = "Limited defenses \u2014 the Hero must stand as the primary bulwark",
            emoji = "\uD83D\uDDE1\uFE0F",
            targetWave = 7,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.HEALER),
            allowedPowers = emptySet(),
            diamondReward = 13,
            hint = "Keep the Hero near Healer auras to regenerate while cleaving through ghouls",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 7, null, "Survive all 7 waves", "Przetrwaj wszystkie 7 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 3, null, "Max 3 towers placed", "Maksymalnie 3 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.MIN_COMBO, 25, null, "Achieve 25x Kill Combo", "Osi\u0105gnij combo 25x")
        ),
        CampaignLevel(
            id = 48,
            title = "The Midas Curse",
            description = "Treasure flows like water, but greed attracts ravenous horrors",
            emoji = "\uD83D\uDCB0",
            targetWave = 10,
            startingGold = 150,
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            goldMult = 2.5f,
            diamondReward = 14,
            hint = "Spend your gold rapidly to upgrade towers before enemies overwhelm the perimeter",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 49,
            title = "Soul Harvest",
            description = "Command the Necromancer towers to raise a protective legion of bone",
            emoji = "\uD83E\uDDB4",
            targetWave = 12,
            startingGold = 240,
            allowedTowers = setOf(TowerType.NECRO, TowerType.MAGIC, TowerType.ICE, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 14,
            hint = "Resurrected skeletons block enemy pathing while Magic towers shred them",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 50,
            title = "Chrono Lich's Domain",
            description = "The ancient master of time bends reality and commands phantom thralls",
            emoji = "\u23F3",
            targetWave = 15,
            startingGold = 320,
            enemyHpMult = 1.3f,
            diamondReward = 16,
            hint = "Beware of time stuns; keep high DPS towers spread out to avoid synchronized shutdown",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Vanquish the Chrono Lich", "Pokonaj Chrono Licza"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich", "Bohater zabija Licza"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 75, null, "Base HP \u2265 75%", "Zdrowie bazy \u2265 75%")
        ),
        CampaignLevel(
            id = 51,
            title = "High Voltage",
            description = "Electrified ramparts \u2014 chain lightning across massive enemy swarms",
            emoji = "\u26A1",
            targetWave = 10,
            startingGold = 250,
            allowedTowers = setOf(TowerType.TESLA, TowerType.HEALER, TowerType.ARROW, TowerType.ICE),
            allowedPowers = setOf(PowerType.LIGHTNING),
            diamondReward = 14,
            hint = "Tesla coils chain to more targets when enemies are slowed by Ice",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Kill Combo", "Osi\u0105gnij combo 40x"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 52,
            title = "Four Pillars",
            description = "Sacred ground allows only 4 towers. Make every placement count",
            emoji = "\uD83C\uDFDB\uFE0F",
            targetWave = 11,
            startingGold = 350,
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            diamondReward = 15,
            hint = "Upgrade all 4 towers to Level 5 and specialize them for maximum coverage",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear all 11 waves", "Przetrwaj wszystkie 11 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 53,
            title = "Tempest Wing",
            description = "Thunderstorms rage as airborne Harpies evade ground artillery",
            emoji = "\uD83E\uDDA5",
            targetWave = 9,
            startingGold = 190,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.MAGIC, TowerType.TESLA),
            diamondReward = 14,
            hint = "Cannons cannot strike airborne targets; rely on Ballista and Tesla",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Survive all 9 waves", "Przetrwaj wszystkie 9 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.CANNON, "No Cannon towers", "Bez dzia\u0142"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 54,
            title = "Zero Arcana",
            description = "Anti-magic suppression field: pure mechanical defense only",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 220,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.BALLISTA, TowerType.HEALER),
            allowedPowers = emptySet(),
            diamondReward = 14,
            hint = "No spells available \u2014 use Ballistas to pierce heavy armor and Cannons for swarms",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 55,
            title = "The Storm Leviathan",
            description = "Colossal sea beast unleashes EMP waves that jam tower capacitors",
            emoji = "\uD83D\uDC09",
            targetWave = 15,
            startingGold = 350,
            enemyHpMult = 1.35f,
            diamondReward = 16,
            hint = "Prepare for EMP charges by moving your Hero into position to deal melee damage",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Slay the Storm Leviathan", "Zg\u0142ad\u017a Lewiatana Burz"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater zabija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 56,
            title = "Shatterpoint",
            description = "Frozen enemies take 3x damage from blunt kinetic bombardment",
            emoji = "\uD83E\uDDCA",
            targetWave = 10,
            startingGold = 230,
            allowedTowers = setOf(TowerType.ICE, TowerType.CANNON, TowerType.BALLISTA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 14,
            hint = "Freeze incoming clusters, then crush them with heavy Cannon mortar rounds",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 45, null, "Achieve 45x Shatter Combo", "Osi\u0105gnij combo 45x"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 57,
            title = "The Glacial Wall",
            description = "Massive frost giants: 300% HP, slow movement, unstoppable march",
            emoji = "\uD83C\uDFD4\uFE0F",
            targetWave = 8,
            startingGold = 280,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.POISON, TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = setOf(PowerType.FIREBALL),
            enemyHpMult = 3.0f,
            enemySpeedMult = 0.5f,
            diamondReward = 15,
            hint = "Stack Poison damage-over-time with high-velocity Ballista bolts",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Slay all Glacier Giants", "Pokonaj Olbrzymy Lodowe"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 5, null, "Max 5 towers placed", "Maksymalnie 5 wie\u017c")
        ),
        CampaignLevel(
            id = 58,
            title = "Frostbite Paradox",
            description = "Bitter cold freezes your Ice towers \u2014 fight back with venom and fire",
            emoji = "\u2744\uFE0F",
            targetWave = 11,
            startingGold = 200,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.POISON, TowerType.FLAME, TowerType.TESLA),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            diamondReward = 15,
            hint = "Use Poison towers for crowd control when Ice is unavailable",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear Wave 11", "Przetrwaj Fal\u0119 11"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ICE, "No Ice towers", "Bez wie\u017c lodu"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 59,
            title = "Avalanche Run",
            description = "Relentless hordes cascade down the snowline every 10 seconds",
            emoji = "\uD83C\uDFC2",
            targetWave = 12,
            startingGold = 160,
            allowedTowers = setOf(TowerType.CANNON, TowerType.FLAME, TowerType.TESLA, TowerType.ICE),
            allowedPowers = setOf(PowerType.FIREBALL),
            spawnRateMult = 1.35f,
            diamondReward = 15,
            hint = "Lay down napalm carpets and cluster bombs at the primary bottleneck",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Survive all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 50, null, "Achieve 50x Avalanche Combo", "Osi\u0105gnij combo 50x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 60,
            title = "Frost Titan's Wrath",
            description = "The Frost Titan unleashes map-wide glacial quakes and ice shields",
            emoji = "\uD83D\uDC51",
            targetWave = 15,
            startingGold = 360,
            enemyHpMult = 1.4f,
            diamondReward = 17,
            hint = "Towers will be stunned at 25% boss HP; position Hero to absorb the seismic shock",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Shatter the Frost Titan", "Zg\u0142ad\u017a Tytana Mrozu"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Titan", "Bohater zabija Tytana"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 61,
            title = "Prismatic Shifters",
            description = "Enemies cycle damage immunities \u2014 mono-type defenses will fall",
            emoji = "\uD83D\uDD2E",
            targetWave = 10,
            startingGold = 250,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.FLAME, TowerType.TESLA, TowerType.BALLISTA),
            diamondReward = 15,
            hint = "Diversify your arsenal: blend physical, elemental, and energy damage",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 62,
            title = "Solar Eclipse",
            description = "Mystic celestial alignment: spell cooldowns cut in half!",
            emoji = "\u2600\uFE0F",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.HEALER, TowerType.MAGIC),
            diamondReward = 15,
            hint = "Cast Fireball and Freeze continuously while your Hero dashes with swiftness",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Combo", "Osi\u0105gnij combo 40x")
        ),
        CampaignLevel(
            id = 63,
            title = "Lone Champion",
            description = "Only 2 towers permitted. The Hero receives 2.5x empowered power",
            emoji = "\uD83E\uDD3A",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = setOf(TowerType.HEALER, TowerType.ICE, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Micro the empowered Hero to intercept leaders while Ice slows the pack",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive with Hero", "Przetrwaj Bohaterem"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 2, null, "Max 2 towers placed", "Maksymalnie 2 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 64,
            title = "Blood Moon Rampage",
            description = "Monsters in frenzy (+25% speed) under the sanguine orb. 2x spoils",
            emoji = "\uD83E\uDE78",
            targetWave = 12,
            startingGold = 200,
            enemyDmgMult = 1.25f,
            enemySpeedMult = 1.25f,
            goldMult = 2.0f,
            diamondReward = 16,
            hint = "High speed enemies mean chokepoints with Ice and Tesla are paramount",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Survive Blood Moon 12 waves", "Przetrwaj 12 fal Krwawego Ksi\u0119\u017cyca"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 65,
            title = "Void Phoenix Ascendant",
            description = "Astral guardian reincarnates upon death into a blazing stellar terror",
            emoji = "\uD83E\uDEB6",
            targetWave = 15,
            startingGold = 380,
            enemyHpMult = 1.4f,
            diamondReward = 18,
            hint = "Save burst abilities for the phoenix's second rebirth phase",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Banish the Void Phoenix", "Wygna\u0142 Feniksa Pustki"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Phoenix", "Bohater zabija Feniksa"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 66,
            title = "Twin Fractures",
            description = "Creeps assault from two separate paths simultaneously. Split defenses",
            emoji = "\u2694\uFE0F",
            targetWave = 12,
            startingGold = 300,
            diamondReward = 16,
            hint = "Distribute gold evenly between east and west corridors",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Hold both corridors 12 waves", "Utrzymaj oba korytarze 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 67,
            title = "The Purist",
            description = "Classic defense: Arrow and Cannon only. No spells, no upgrades",
            emoji = "\uD83C\uDFF9",
            targetWave = 14,
            startingGold = 160,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            diamondReward = 17,
            hint = "Position Cannons to hit maximum intersections, and use Arrows for cleanup",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Clear all 14 waves", "Przetrwaj wszystkie 14 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 68,
            title = "The Iron Colosseum",
            description = "Armored behemoths and stone dreadnoughts withstand ordinary attacks",
            emoji = "\uD83E\uDD16",
            targetWave = 12,
            startingGold = 320,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.FLAME, TowerType.MAGIC, TowerType.POISON),
            allowedPowers = setOf(PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Armor Piercing Ballistas and Napalm melt dense metallic shells",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 69,
            title = "The Boss Gauntlet",
            description = "Ten consecutive waves, ten relentless bosses. An unbroken trial",
            emoji = "\uD83D\uDC79",
            targetWave = 10,
            startingGold = 400,
            diamondReward = 20,
            hint = "A boss appears every wave \u2014 single target burst DPS is essential",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Survive all 10 Boss Waves", "Przetrwaj 10 Fal Boss\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 75, null, "Base HP \u2265 75%", "Zdrowie bazy \u2265 75%"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 8, null, "Max 8 towers placed", "Maksymalnie 8 wie\u017c")
        ),
        CampaignLevel(
            id = 70,
            title = "The Omni-Sovereign",
            description = "The ultimate cataclysm \u2014 the Omni-Sovereign commands all elements",
            emoji = "\uD83E\uDD34",
            targetWave = 20,
            startingGold = 450,
            enemyHpMult = 1.5f,
            enemyDmgMult = 1.4f,
            diamondReward = 25,
            hint = "Counters every element. Transition between kinetic, magic, and flame across 4 phases",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 20, null, "Vanquish the Omni-Sovereign", "Pokonaj Wszech-W\u0142adc\u0119"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero delivers finishing blow", "Bohater zadaje ostateczny cios"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 71,
            title = "Draugr's Awakening",
            description = "Frozen ancient skeletons freeze upon death, causing chain reactions",
            emoji = "\uD83E\uDEE6",
            targetWave = 11,
            startingGold = 220,
            allowedTowers = setOf(TowerType.ARROW, TowerType.ICE, TowerType.CANNON, TowerType.MAGIC),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Shatter frozen Draugr with Cannon shells to trigger shrapnel bursts",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear all 11 waves", "Przetrwaj wszystkie 11 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Shatter Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 72,
            title = "Soul-Frost Conduit",
            description = "Necromancer skeletons inherit chilling permafrost auras",
            emoji = "\uD83D\uDC7B",
            targetWave = 10,
            startingGold = 240,
            allowedTowers = setOf(TowerType.NECRO, TowerType.ICE, TowerType.MAGIC, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Pair Healer towers with Necromancers to sustain freezing bone legions",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 73,
            title = "The Frozen Phylactery",
            description = "Lich warlord protected by a frost ward \u2014 Hero must break the altar",
            emoji = "\uD83C\uDFFA",
            targetWave = 12,
            startingGold = 260,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.FLAME, TowerType.TESLA),
            allowedPowers = setOf(PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Move Hero into the fray to shatter the phylactery while towers provide cover",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Destroy Phylactery 12 waves", "Zniszcz Filakterium 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich", "Bohater zabija Licza"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 74,
            title = "Black Ice Run",
            description = "Glacial speed rush (+60% velocity) \u2014 melt traction with napalm",
            emoji = "\u26F8\uFE0F",
            targetWave = 9,
            startingGold = 190,
            allowedTowers = setOf(TowerType.FLAME, TowerType.POISON, TowerType.TESLA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            enemyHpMult = 0.75f,
            enemySpeedMult = 1.6f,
            diamondReward = 16,
            hint = "Flame towers strip the ice speed boost and cause burning stalls",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Survive all 9 waves", "Przetrwaj wszystkie 9 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ICE, "No Ice towers", "Bez wie\u017c lodu"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 5, null, "Max 5 towers placed", "Maksymalnie 5 wie\u017c")
        ),
        CampaignLevel(
            id = 75,
            title = "Frost-Bane Necromancer",
            description = "Blizzard sorcerer freezes defenses and raises frost ghouls",
            emoji = "\uD83E\uDDD9\u200D\u2642\uFE0F",
            targetWave = 14,
            startingGold = 320,
            diamondReward = 18,
            hint = "Ballistas with Armor Piercer bypass the ghouls' hardened frost plating",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Defeat Frost-Bane Necromancer", "Pokonaj Mro\u017anego Nekromant\u0119"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 76,
            title = "Corpse Shatter",
            description = "Frozen corpses ignite into secondary blasts from mortar impacts",
            emoji = "\uD83D\uDCA5",
            targetWave = 12,
            startingGold = 230,
            allowedTowers = setOf(TowerType.CANNON, TowerType.ICE, TowerType.BALLISTA, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Cluster enemies at corners where frozen bodies multiply mortar splash",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 45, null, "Achieve 45x Shatter Combo", "Osi\u0105gnij combo 45x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 77,
            title = "The Whispering Mist",
            description = "Stealth phantoms stalk the swamp \u2014 illuminated only by aura and hero",
            emoji = "\uD83D\uDC7B",
            targetWave = 10,
            startingGold = 210,
            allowedTowers = setOf(TowerType.HEALER, TowerType.MAGIC, TowerType.TESLA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.LIGHTNING),
            diamondReward = 17,
            hint = "Healer Sanctuary auras reveal hidden specters so turrets can target them",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 78,
            title = "Glacial Perma-Death",
            description = "Zero base repairs. Zero sell refunds. Pure irrevocable survival",
            emoji = "\u2620\uFE0F",
            targetWave = 8,
            startingGold = 300,
            allowedPowers = setOf(PowerType.FREEZE, PowerType.LIGHTNING),
            diamondReward = 18,
            hint = "Every hit to your base is permanent. Invest in layered control grids",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 79,
            title = "Cryo-Cataclysm",
            description = "Volcano under freeze: odd waves fire-immune, even waves ice-immune",
            emoji = "\u267B\uFE0F",
            targetWave = 13,
            startingGold = 280,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE, TowerType.CANNON, TowerType.MAGIC, TowerType.BALLISTA),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            diamondReward = 18,
            hint = "Build an alternating chessboard pattern of Flame and Ice towers",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 13, null, "Clear 13 alternating waves", "Przetrwaj 13 fal naprzemiennych"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 80,
            title = "The Glacial Lich-King",
            description = "Master of death and winter. 4-phase combat culminating in Absolute Zero",
            emoji = "\uD83E\uDDCA",
            targetWave = 20,
            startingGold = 420,
            enemyHpMult = 1.6f,
            enemyDmgMult = 1.5f,
            diamondReward = 30,
            hint = "Burst down the final phase with everything you have before Absolute Zero detonates",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 20, null, "Vanquish the Glacial Lich-King", "Zg\u0142ad\u017a Kr\u00f3la Licz\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich-King", "Bohater zabija Kr\u00f3la Licz\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        )
    )
}