package com.example.myapp.game

data class CampaignLevel(
    val id: Int,
    val title: String,
    val description: String,
    val emoji: String,
    val targetWave: Int,
    val startingGold: Int = 50,
    val allowedTowers: Set<TowerType> = TowerType.entries.toSet(),
    val allowedPowers: Set<PowerType> = PowerType.entries.toSet(),
    val upgradesEnabled: Boolean = true,
    val enemyHpMult: Float = 1f,
    val enemyDmgMult: Float = 1f,
    val enemySpeedMult: Float = 1f,
    val goldMult: Float = 1f,
    val spawnRateMult: Float = 1f,
    val diamondReward: Int = 3,
    val hint: String = "",
    val mapType: MapType = MapType.CLASSIC
) {
    /** Estimate the base score (gold from kills without combos) for this level. */
    private fun estimatedBaseScore(): Int {
        var total = 0f
        val bossInterval = 5
        for (w in 1..targetWave) {
            val waveScale = 1f + (w - 1) * 0.15f
            if (w % bossInterval == 0) {
                // Boss gold + ~5 minions
                val bossGold = (50f + w * 10f) * waveScale * goldMult
                val minionGold = 5 * 5f * waveScale * goldMult
                total += bossGold + minionGold
            } else {
                val count = ((3 + w * 2) * spawnRateMult).toInt()
                val avgGold = 5f + w * 0.8f
                total += count * avgGold * waveScale * goldMult
            }
        }
        return total.toInt()
    }

    /** Score needed for 2 stars — requires decent play with some combo chaining. */
    val star2Score: Int get() = (estimatedBaseScore() * 0.8f).toInt().coerceAtLeast(50)

    /** Score needed for 3 stars — requires sustained high combos and efficient kills. */
    val star3Score: Int get() = (estimatedBaseScore() * 1.5f).toInt().coerceAtLeast(100)
}

object CampaignData {

    val levels = listOf(
        CampaignLevel(
            id = 1,
            title = "The Basics",
            description = "Place Arrow towers to stop the goblins!",
            emoji = "\uD83C\uDFF9",
            targetWave = 3,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.6f, enemyDmgMult = 0.5f, enemySpeedMult = 0.8f,
            goldMult = 1.5f,
            diamondReward = 2,
            hint = "Tap a tower button, then tap the field to place it",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 2,
            title = "Magic Touch",
            description = "Magic towers deal more damage but cost more",
            emoji = "\uD83E\uDDE8",
            targetWave = 4,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.7f, enemyDmgMult = 0.6f, enemySpeedMult = 0.85f,
            goldMult = 1.3f,
            diamondReward = 2,
            hint = "Mix Arrow and Magic towers for best coverage",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 3,
            title = "Heavy Artillery",
            description = "Cannons have splash potential — use them wisely",
            emoji = "\uD83D\uDCA3",
            targetWave = 5,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 3,
            hint = "Cannons are expensive but powerful",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 4,
            title = "Upgrades!",
            description = "Learn to upgrade your towers and hero",
            emoji = "\u2B06\uFE0F",
            targetWave = 5,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f, enemySpeedMult = 0.9f,
            goldMult = 1.3f,
            diamondReward = 3,
            hint = "Tap a tower to select it, then press ⬆ TOWER to upgrade",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 5,
            title = "Boss Battle",
            description = "Survive the first boss encounter!",
            emoji = "\u2620\uFE0F",
            targetWave = 5,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Every 5th wave is a boss wave — prepare your defenses!",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 6,
            title = "Open Armory",
            description = "All 10 tower types unlocked — experiment with every combo!",
            emoji = "\uD83D\uDD13",
            targetWave = 7,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.1f,
            diamondReward = 4,
            hint = "ICE slows enemies, TESLA chains lightning, POISON deals damage over time — try them all!",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 7,
            title = "Power Surge",
            description = "Learn to use powers in combat",
            emoji = "\uD83D\uDD25",
            targetWave = 7,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Fireball damages all enemies. Freeze slows them down!",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 8,
            title = "Full Arsenal",
            description = "All powers unlocked — master them all",
            emoji = "\u26A1",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 1f,
            goldMult = 1f,
            diamondReward = 5,
            hint = "Heal repairs your base, Lightning chains between enemies",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 9,
            title = "The Horde",
            description = "Wave after wave of massive enemy numbers",
            emoji = "\uD83D\uDC80",
            targetWave = 10,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.9f,
            spawnRateMult = 1.5f, goldMult = 0.9f,
            diamondReward = 5,
            hint = "Lots of enemies incoming — build wide coverage",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 10,
            title = "Tower Budget",
            description = "Gold is scarce — spend wisely!",
            emoji = "\uD83D\uDCB0",
            targetWave = 8,
            startingGold = 30,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 0.6f,
            diamondReward = 5,
            hint = "Every coin counts — upgrade instead of building new",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 11,
            title = "Speed Demons",
            description = "Enemies move fast — freeze is your friend",
            emoji = "\uD83D\uDCA8",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.8f,
            enemySpeedMult = 1.5f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Use Freeze power when enemies get close to the base",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 12,
            title = "Iron Wall",
            description = "Enemies are tough — bring your best",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.5f, enemyDmgMult = 1.3f,
            enemySpeedMult = 0.9f, goldMult = 1.2f,
            diamondReward = 6,
            hint = "Upgrade towers to deal with armored enemies",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 13,
            title = "Champions Arise",
            description = "The enemy's champions march — two boss waves await you",
            emoji = "\uD83D\uDC09",
            targetWave = 10,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Boss enemies appear at waves 5 and 10 — save gold between each for quick upgrades",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 14,
            title = "Arrows Only",
            description = "Only Arrow towers allowed — pure skill",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Upgrade your arrows and use powers to compensate",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 15,
            title = "Night Raid",
            description = "Darkness falls — enemies are stronger at night",
            emoji = "\uD83C\uDF19",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            goldMult = 1.2f,
            diamondReward = 6,
            hint = "Night increases enemy HP by 20% and reduces tower range",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 16,
            title = "Swarm Tactics",
            description = "Double enemies, half HP — overwhelm or be overwhelmed",
            emoji = "\uD83D\uDC1C",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.5f, enemyDmgMult = 0.7f,
            spawnRateMult = 2f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Many weak enemies — use splash damage towers!",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 17,
            title = "Sealed Powers",
            description = "An ancient curse seals your powers — can your towers hold the line?",
            emoji = "\uD83D\uDD12",
            targetWave = 8,
            startingGold = 140,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "No powers — smart tower placement and upgrading is your only weapon",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 18,
            title = "Elite Forces",
            description = "Elite enemies appear every wave — be ready",
            emoji = "\uD83D\uDC51",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 8,
            hint = "Elite enemies have 3x HP and 2x gold — focus fire them",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 19,
            title = "The Crucible",
            description = "12 relentless waves — only the most prepared will survive",
            emoji = "\uD83D\uDD25",
            targetWave = 12,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            spawnRateMult = 1.3f,
            diamondReward = 9,
            hint = "Pace yourself — upgrade towers every few waves and don't spend everything at once",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 20,
            title = "Final Stand",
            description = "The ultimate challenge — can you survive?",
            emoji = "\uD83C\uDFC6",
            targetWave = 15,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f, enemyDmgMult = 1.3f,
            enemySpeedMult = 1.1f, goldMult = 0.9f,
            spawnRateMult = 1.2f,
            diamondReward = 10,
            hint = "Use everything you've learned. Good luck!",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 21,
            title = "Poison Mastery",
            description = "Only Poison towers — let them wither",
            emoji = "\u2620\uFE0F",
            targetWave = 8,
            startingGold = 130,
            allowedTowers = setOf(TowerType.POISON),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Poison does damage over time — place towers where enemies linger",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 22,
            title = "Chain Reaction",
            description = "Tesla towers only — every enemy is a link in the chain",
            emoji = "\u26A1",
            targetWave = 8,
            startingGold = 150,
            allowedTowers = setOf(TowerType.TESLA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.85f, enemyDmgMult = 0.8f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "Tesla chains to 3 nearby enemies — let groups of enemies cluster before shooting",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 23,
            title = "Frozen Fortress",
            description = "Ice slow + firepower combo on the Snow map",
            emoji = "\u2744\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ICE, TowerType.ARROW, TowerType.CANNON),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            enemySpeedMult = 1.2f, goldMult = 1.1f,
            diamondReward = 8,
            hint = "Ice towers slow, then cannons and arrows finish them off",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 24,
            title = "No Upgrades",
            description = "Hero upgrades disabled — raw tower power only",
            emoji = "\uD83D\uDEAB",
            targetWave = 10,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = false,
            enemyHpMult = 0.9f, enemyDmgMult = 0.85f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Spend all gold on towers and their upgrades",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 25,
            title = "Desert Siege",
            description = "Fight across the scorching desert terrain",
            emoji = "\uD83C\uDFDC\uFE0F",
            targetWave = 12,
            startingGold = 90,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            diamondReward = 9,
            hint = "Desert enemies are tough but you have every tool available",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 26,
            title = "Triple Threat",
            description = "Survive three boss waves — prepare between each one",
            emoji = "\uD83D\uDC80\uD83D\uDC80",
            targetWave = 15,
            startingGold = 130,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            goldMult = 1.4f,
            diamondReward = 10,
            hint = "Boss enemies at waves 5, 10, and 15 — rush upgrades after each boss kill",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 27,
            title = "Toxin Tide",
            description = "Poison weakens, Flame burns — stack damage over time to melt them",
            emoji = "\u2623\uFE0F",
            targetWave = 10,
            startingGold = 110,
            allowedTowers = setOf(TowerType.ARROW, TowerType.POISON, TowerType.FLAME),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f, enemyDmgMult = 1.1f,
            goldMult = 1.1f,
            diamondReward = 8,
            hint = "Poison and Flame both deal damage over time — enemies that survive long take double punishment",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 28,
            title = "Brittle Bastion",
            description = "Your base is barely standing — don't let a single enemy through",
            emoji = "\uD83D\uDCA5",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.7f, enemyDmgMult = 1.5f,
            goldMult = 1.3f,
            diamondReward = 9,
            hint = "Even one enemy reaching the base could be fatal — build a complete forward defense",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 29,
            title = "The Marathon",
            description = "20 waves of escalating madness",
            emoji = "\uD83C\uDFC3",
            targetWave = 20,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.05f, goldMult = 1f,
            spawnRateMult = 1.1f,
            diamondReward = 12,
            hint = "Pace yourself — this is a long fight. Save gold for late waves.",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 30,
            title = "True Champion",
            description = "The hardest challenge — prove your mastery",
            emoji = "\uD83D\uDC8E",
            targetWave = 20,
            startingGold = 50,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.6f, enemyDmgMult = 1.5f,
            enemySpeedMult = 1.15f, goldMult = 0.8f,
            spawnRateMult = 1.3f,
            diamondReward = 15,
            hint = "Everything is against you. Only the best will survive.",
            mapType = MapType.VOLCANO
        ),

        // ========== NEW TOWER LEVELS (31-40) ==========
        CampaignLevel(
            id = 31,
            title = "Playing with Fire",
            description = "Flame towers unlock — burn them all!",
            emoji = "\uD83D\uDD25",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.FLAME),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 6,
            hint = "Flame towers burn enemies over time — great against regen!",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 32,
            title = "Dark Arts",
            description = "Necro towers execute weakened enemies",
            emoji = "\uD83D\uDC80",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.NECRO),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 0.9f,
            goldMult = 1.1f,
            diamondReward = 7,
            hint = "Necro towers deal 3× damage to enemies below 15% HP!",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 33,
            title = "Siege Warfare",
            description = "Ballista towers snipe from extreme range",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Ballista has huge range and damage but fires very slowly",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 34,
            title = "Event Horizon",
            description = "Vortex towers pull enemies to their doom",
            emoji = "\uD83C\uDF00",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.VORTEX, TowerType.CANNON, TowerType.ICE),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "Vortex pulls enemies together — combo with Cannon splash!",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 35,
            title = "Fire & Ice",
            description = "Opposite elements — slow them, then burn them",
            emoji = "\u2744\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.2f, goldMult = 1.1f,
            diamondReward = 8,
            hint = "Ice slows, Flame burns — the classic combo",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 36,
            title = "Necro Rush",
            description = "Swarms of weak enemies — harvest their souls",
            emoji = "\uD83D\uDC80",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.NECRO, TowerType.POISON, TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.6f, enemyDmgMult = 0.7f,
            spawnRateMult = 2.5f, goldMult = 1f,
            diamondReward = 8,
            hint = "Huge swarms — Poison weakens them, Necro executes!",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 37,
            title = "Gravity Well",
            description = "Only Vortex and Tesla — pull and shock",
            emoji = "\uD83C\uDF00",
            targetWave = 10,
            startingGold = 130,
            allowedTowers = setOf(TowerType.VORTEX, TowerType.TESLA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.2f,
            diamondReward = 9,
            hint = "Vortex groups enemies, Tesla chains between them!",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 38,
            title = "Dead Eye",
            description = "Ballista and Ice — freeze them, then pick them off one by one",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.ICE),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 10,
            hint = "ICE slows enemies nearly to a stop — Ballista then dismantles them before the freeze wears off",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 39,
            title = "Full Armory",
            description = "All 10 towers — master every type!",
            emoji = "\uD83C\uDFF0",
            targetWave = 15,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f, enemyDmgMult = 1.2f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            diamondReward = 12,
            hint = "All 10 tower types available — use synergies wisely!",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 40,
            title = "Absolute Zero",
            description = "The ultimate test — everything maxed against you",
            emoji = "\uD83D\uDC8E",
            targetWave = 25,
            startingGold = 60,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.8f, enemyDmgMult = 1.6f,
            enemySpeedMult = 1.2f, goldMult = 0.7f,
            spawnRateMult = 1.4f,
            diamondReward = 20,
            hint = "The hardest level in the game. Good luck.",
            mapType = MapType.VOLCANO
        )
    )
}
