package com.example.myapp.game

enum class ObjectiveType {
    SURVIVE_WAVES,
    PERFECT_BASE,        // 0 base damage taken
    BASE_HP_ABOVE,       // Base HP >= targetValue% (e.g. 80)
    NO_TOWERS_SOLD,      // No towers sold
    MAX_TOWERS_PLACED,   // Total towers placed <= targetValue
    FORBIDDEN_TOWER,     // Never placed forbiddenTower
    NO_POWERS_USED,      // powersUsed == 0
    MIN_COMBO,           // bestCombo >= targetValue
    HERO_SLAYS_BOSS      // Hero delivered fatal damage to a boss
}

data class CampaignObjective(
    val type: ObjectiveType,
    val targetValue: Int = 0,
    val forbiddenTower: TowerType? = null,
    val descEn: String,
    val descPl: String
) {
    fun description(isPl: Boolean): String = if (isPl) descPl else descEn
}

data class CampaignLevel(
    val id: Int,
    val title: String,
    val description: String,
    val emoji: String,
    val targetWave: Int,
    val startingGold: Int = 50,
    val allowedTowers: Set<TowerType> = TowerType.entries.toSet(),
    val allowedPowers: Set<PowerType> = PowerType.entries.toSet(),
    val upgradesEnabled: Boolean = true,
    val enemyHpMult: Float = 1f,
    val enemyDmgMult: Float = 1f,
    val enemySpeedMult: Float = 1f,
    val goldMult: Float = 1f,
    val spawnRateMult: Float = 1f,
    val diamondReward: Int = 3,
    val hint: String = "",
    val mapType: MapType = MapType.CLASSIC,
    val objective1: CampaignObjective = CampaignObjective(
        ObjectiveType.SURVIVE_WAVES,
        targetWave,
        null,
        "Clear all $targetWave waves",
        "Przetrwaj wszystkie $targetWave fale"
    ),
    val objective2: CampaignObjective = CampaignObjective(
        ObjectiveType.PERFECT_BASE,
        0,
        null,
        "Flawless Citadel (0 Base Damage)",
        "Nienaruszona Cytadela (0 obrażeń bazy)"
    ),
    val objective3: CampaignObjective = CampaignObjective(
        ObjectiveType.NO_TOWERS_SOLD,
        0,
        null,
        "Tactical Discipline (No towers sold)",
        "Dyscyplina Taktyczna (Bez sprzedaży wież)"
    )
) {
    /** Estimate the base score (gold from kills without combos) for this level. */
    private fun estimatedBaseScore(): Int {
        var total = 0f
        val bossInterval = 5
        for (w in 1..targetWave) {
            val waveScale = 1f + (w - 1) * 0.15f
            if (w % bossInterval == 0) {
                // Boss gold + ~5 minions
                val bossGold = (50f + w * 10f) * waveScale * goldMult
                val minionGold = 5 * 5f * waveScale * goldMult
                total += bossGold + minionGold
            } else {
                val count = ((3 + w * 2) * spawnRateMult).toInt()
                val avgGold = 5f + w * 0.8f
                total += count * avgGold * waveScale * goldMult
            }
        }
        return total.toInt()
    }

    /** Score needed for 2 stars — requires decent play with some combo chaining. */
    val star2Score: Int get() = (estimatedBaseScore() * 0.8f).toInt().coerceAtLeast(50)

    /** Score needed for 3 stars — requires sustained high combos and efficient kills. */
    val star3Score: Int get() = (estimatedBaseScore() * 1.5f).toInt().coerceAtLeast(100)
}

object CampaignData {

    val levels = listOf(
        CampaignLevel(
            id = 1,
            title = "The Basics",
            description = "Place Arrow towers to stop the goblins!",
            emoji = "\uD83C\uDFF9",
            targetWave = 3,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.6f, enemyDmgMult = 0.5f, enemySpeedMult = 0.8f,
            goldMult = 1.5f,
            diamondReward = 2,
            hint = "Tap a tower button, then tap the field to place it",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 2,
            title = "Magic Touch",
            description = "Magic towers deal more damage but cost more",
            emoji = "\uD83E\uDDE8",
            targetWave = 4,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.7f, enemyDmgMult = 0.6f, enemySpeedMult = 0.85f,
            goldMult = 1.3f,
            diamondReward = 2,
            hint = "Mix Arrow and Magic towers for best coverage",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 3,
            title = "Heavy Artillery",
            description = "Cannons have splash potential — use them wisely",
            emoji = "\uD83D\uDCA3",
            targetWave = 5,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 3,
            hint = "Cannons are expensive but powerful",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 4,
            title = "Upgrades!",
            description = "Learn to upgrade your towers and hero",
            emoji = "\u2B06\uFE0F",
            targetWave = 5,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f, enemySpeedMult = 0.9f,
            goldMult = 1.3f,
            diamondReward = 3,
            hint = "Tap a tower to select it, then press ⬆ TOWER to upgrade",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 5,
            title = "Boss Battle",
            description = "Survive the first boss encounter!",
            emoji = "\u2620\uFE0F",
            targetWave = 5,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Every 5th wave is a boss wave — prepare your defenses!",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 6,
            title = "Open Armory",
            description = "All 10 tower types unlocked — experiment with every combo!",
            emoji = "\uD83D\uDD13",
            targetWave = 7,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.1f,
            diamondReward = 4,
            hint = "ICE slows enemies, TESLA chains lightning, POISON deals damage over time — try them all!",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 7,
            title = "Power Surge",
            description = "Learn to use powers in combat",
            emoji = "\uD83D\uDD25",
            targetWave = 7,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Fireball damages all enemies. Freeze slows them down!",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 8,
            title = "Full Arsenal",
            description = "All powers unlocked — master them all",
            emoji = "\u26A1",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 1f,
            goldMult = 1f,
            diamondReward = 5,
            hint = "Heal repairs your base, Lightning chains between enemies",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 9,
            title = "The Horde",
            description = "Wave after wave of massive enemy numbers",
            emoji = "\uD83D\uDC80",
            targetWave = 10,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.9f,
            spawnRateMult = 1.5f, goldMult = 0.9f,
            diamondReward = 5,
            hint = "Lots of enemies incoming — build wide coverage",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 10,
            title = "Tower Budget",
            description = "Gold is scarce — spend wisely!",
            emoji = "\uD83D\uDCB0",
            targetWave = 8,
            startingGold = 30,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 0.6f,
            diamondReward = 5,
            hint = "Every coin counts — upgrade instead of building new",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 11,
            title = "Speed Demons",
            description = "Enemies move fast — freeze is your friend",
            emoji = "\uD83D\uDCA8",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.8f,
            enemySpeedMult = 1.5f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Use Freeze power when enemies get close to the base",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 12,
            title = "Iron Wall",
            description = "Enemies are tough — bring your best",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.5f, enemyDmgMult = 1.3f,
            enemySpeedMult = 0.9f, goldMult = 1.2f,
            diamondReward = 6,
            hint = "Upgrade towers to deal with armored enemies",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 13,
            title = "Champions Arise",
            description = "The enemy's champions march — two boss waves await you",
            emoji = "\uD83D\uDC09",
            targetWave = 10,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Boss enemies appear at waves 5 and 10 — save gold between each for quick upgrades",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 14,
            title = "Arrows Only",
            description = "Only Arrow towers allowed — pure skill",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Upgrade your arrows and use powers to compensate",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 15,
            title = "Night Raid",
            description = "Darkness falls — enemies are stronger at night",
            emoji = "\uD83C\uDF19",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            goldMult = 1.2f,
            diamondReward = 6,
            hint = "Night increases enemy HP by 20% and reduces tower range",
            mapType = MapType.CLASSIC
        ),
        CampaignLevel(
            id = 16,
            title = "Swarm Tactics",
            description = "Double enemies, half HP — overwhelm or be overwhelmed",
            emoji = "\uD83D\uDC1C",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.5f, enemyDmgMult = 0.7f,
            spawnRateMult = 2f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Many weak enemies — use splash damage towers!",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 17,
            title = "Sealed Powers",
            description = "An ancient curse seals your powers — can your towers hold the line?",
            emoji = "\uD83D\uDD12",
            targetWave = 8,
            startingGold = 140,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "No powers — smart tower placement and upgrading is your only weapon",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 18,
            title = "Elite Forces",
            description = "Elite enemies appear every wave — be ready",
            emoji = "\uD83D\uDC51",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 8,
            hint = "Elite enemies have 3x HP and 2x gold — focus fire them",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 19,
            title = "The Crucible",
            description = "12 relentless waves — only the most prepared will survive",
            emoji = "\uD83D\uDD25",
            targetWave = 12,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            spawnRateMult = 1.3f,
            diamondReward = 9,
            hint = "Pace yourself — upgrade towers every few waves and don't spend everything at once",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 20,
            title = "Final Stand",
            description = "The ultimate challenge — can you survive?",
            emoji = "\uD83C\uDFC6",
            targetWave = 15,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f, enemyDmgMult = 1.3f,
            enemySpeedMult = 1.1f, goldMult = 0.9f,
            spawnRateMult = 1.2f,
            diamondReward = 10,
            hint = "Use everything you've learned. Good luck!",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 21,
            title = "Poison Mastery",
            description = "Only Poison towers — let them wither",
            emoji = "\u2620\uFE0F",
            targetWave = 8,
            startingGold = 130,
            allowedTowers = setOf(TowerType.POISON),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Poison does damage over time — place towers where enemies linger",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 22,
            title = "Chain Reaction",
            description = "Tesla towers only — every enemy is a link in the chain",
            emoji = "\u26A1",
            targetWave = 8,
            startingGold = 150,
            allowedTowers = setOf(TowerType.TESLA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.85f, enemyDmgMult = 0.8f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "Tesla chains to 3 nearby enemies — let groups of enemies cluster before shooting",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 23,
            title = "Frozen Fortress",
            description = "Ice slow + firepower combo on the Snow map",
            emoji = "\u2744\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ICE, TowerType.ARROW, TowerType.CANNON),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            enemySpeedMult = 1.2f, goldMult = 1.1f,
            diamondReward = 8,
            hint = "Ice towers slow, then cannons and arrows finish them off",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 24,
            title = "No Upgrades",
            description = "Hero upgrades disabled — raw tower power only",
            emoji = "\uD83D\uDEAB",
            targetWave = 10,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = false,
            enemyHpMult = 0.9f, enemyDmgMult = 0.85f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Spend all gold on towers and their upgrades",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 25,
            title = "Desert Siege",
            description = "Fight across the scorching desert terrain",
            emoji = "\uD83C\uDFDC\uFE0F",
            targetWave = 12,
            startingGold = 90,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            diamondReward = 9,
            hint = "Desert enemies are tough but you have every tool available",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 26,
            title = "Triple Threat",
            description = "Survive three boss waves — prepare between each one",
            emoji = "\uD83D\uDC80\uD83D\uDC80",
            targetWave = 15,
            startingGold = 130,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            goldMult = 1.4f,
            diamondReward = 10,
            hint = "Boss enemies at waves 5, 10, and 15 — rush upgrades after each boss kill",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 27,
            title = "Toxin Tide",
            description = "Poison weakens, Flame burns — stack damage over time to melt them",
            emoji = "\u2623\uFE0F",
            targetWave = 10,
            startingGold = 110,
            allowedTowers = setOf(TowerType.ARROW, TowerType.POISON, TowerType.FLAME),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f, enemyDmgMult = 1.1f,
            goldMult = 1.1f,
            diamondReward = 8,
            hint = "Poison and Flame both deal damage over time — enemies that survive long take double punishment",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 28,
            title = "Brittle Bastion",
            description = "Your base is barely standing — don't let a single enemy through",
            emoji = "\uD83D\uDCA5",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.7f, enemyDmgMult = 1.5f,
            goldMult = 1.3f,
            diamondReward = 9,
            hint = "Even one enemy reaching the base could be fatal — build a complete forward defense",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 29,
            title = "The Marathon",
            description = "20 waves of escalating madness",
            emoji = "\uD83C\uDFC3",
            targetWave = 20,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.05f, goldMult = 1f,
            spawnRateMult = 1.1f,
            diamondReward = 12,
            hint = "Pace yourself — this is a long fight. Save gold for late waves.",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 30,
            title = "True Champion",
            description = "The hardest challenge — prove your mastery",
            emoji = "\uD83D\uDC8E",
            targetWave = 20,
            startingGold = 50,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.6f, enemyDmgMult = 1.5f,
            enemySpeedMult = 1.15f, goldMult = 0.8f,
            spawnRateMult = 1.3f,
            diamondReward = 15,
            hint = "Everything is against you. Only the best will survive.",
            mapType = MapType.VOLCANO
        ),

        // ========== NEW TOWER LEVELS (31-40) ==========
        CampaignLevel(
            id = 31,
            title = "Playing with Fire",
            description = "Flame towers unlock — burn them all!",
            emoji = "\uD83D\uDD25",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.FLAME),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 6,
            hint = "Flame towers burn enemies over time — great against regen!",
            mapType = MapType.LAVA
        ),
        CampaignLevel(
            id = 32,
            title = "Dark Arts",
            description = "Necro towers execute weakened enemies",
            emoji = "\uD83D\uDC80",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.NECRO),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 0.9f,
            goldMult = 1.1f,
            diamondReward = 7,
            hint = "Necro towers deal 3× damage to enemies below 15% HP!",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 33,
            title = "Siege Warfare",
            description = "Ballista towers snipe from extreme range",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1f,
            goldMult = 1.2f,
            diamondReward = 8,
            hint = "Ballista has huge range and damage but fires very slowly",
            mapType = MapType.DESERT
        ),
        CampaignLevel(
            id = 34,
            title = "Event Horizon",
            description = "Vortex towers pull enemies to their doom",
            emoji = "\uD83C\uDF00",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = setOf(TowerType.VORTEX, TowerType.CANNON, TowerType.ICE),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "Vortex pulls enemies together — combo with Cannon splash!",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 35,
            title = "Fire & Ice",
            description = "Opposite elements — slow them, then burn them",
            emoji = "\u2744\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.2f, goldMult = 1.1f,
            diamondReward = 8,
            hint = "Ice slows, Flame burns — the classic combo",
            mapType = MapType.SNOW
        ),
        CampaignLevel(
            id = 36,
            title = "Necro Rush",
            description = "Swarms of weak enemies — harvest their souls",
            emoji = "\uD83D\uDC80",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = setOf(TowerType.NECRO, TowerType.POISON, TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.6f, enemyDmgMult = 0.7f,
            spawnRateMult = 2.5f, goldMult = 1f,
            diamondReward = 8,
            hint = "Huge swarms — Poison weakens them, Necro executes!",
            mapType = MapType.VALLEY
        ),
        CampaignLevel(
            id = 37,
            title = "Gravity Well",
            description = "Only Vortex and Tesla — pull and shock",
            emoji = "\uD83C\uDF00",
            targetWave = 10,
            startingGold = 130,
            allowedTowers = setOf(TowerType.VORTEX, TowerType.TESLA),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.2f,
            diamondReward = 9,
            hint = "Vortex groups enemies, Tesla chains between them!",
            mapType = MapType.ENCHANTED
        ),
        CampaignLevel(
            id = 38,
            title = "Dead Eye",
            description = "Ballista and Ice — freeze them, then pick them off one by one",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.ICE),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 10,
            hint = "ICE slows enemies nearly to a stop — Ballista then dismantles them before the freeze wears off",
            mapType = MapType.CROSSROADS
        ),
        CampaignLevel(
            id = 39,
            title = "Full Armory",
            description = "All 10 towers — master every type!",
            emoji = "\uD83C\uDFF0",
            targetWave = 15,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.3f, enemyDmgMult = 1.2f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            diamondReward = 12,
            hint = "All 10 tower types available — use synergies wisely!",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 40,
            title = "Absolute Zero",
            description = "The ultimate test — everything maxed against you",
            emoji = "\uD83D\uDC8E",
            targetWave = 25,
            startingGold = 60,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.8f, enemyDmgMult = 1.6f,
            enemySpeedMult = 1.2f, goldMult = 0.7f,
            spawnRateMult = 1.4f,
            diamondReward = 20,
            hint = "The hardest level in the game. Good luck.",
            mapType = MapType.VOLCANO
        ),
        CampaignLevel(
            id = 41,
            title = "Thermal Shockwave",
            description = "Trigger Fire and Ice combinations to shatter magma beasts",
            emoji = "\uD83C\uDF0B",
            targetWave = 10,
            startingGold = 220,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            enemyHpMult = 1.2f,
            enemyDmgMult = 1.1f,
            diamondReward = 12,
            hint = "Pair Flame and Ice towers closely together to trigger thermal explosions",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 42,
            title = "The Red Gauntlet",
            description = "High-speed desert skirmish \u2014 rapid firing required",
            emoji = "\uD83C\uDFDC\uFE0F",
            targetWave = 8,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.TESLA),
            allowedPowers = setOf(PowerType.LIGHTNING),
            enemyHpMult = 0.75f,
            enemySpeedMult = 1.45f,
            diamondReward = 12,
            hint = "Place rapid-firing Arrow and Ballista towers with quick target acquisition",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 6, null, "Max 6 towers placed", "Maksymalnie 6 postawionych wie\u017c")
        ),
        CampaignLevel(
            id = 43,
            title = "Glass Citadel",
            description = "Base HP capped at 10! A single breach spells ruin",
            emoji = "\uD83C\uDFF0",
            targetWave = 12,
            startingGold = 400,
            allowedTowers = TowerType.entries.filter { it != TowerType.HEALER }.toSet(),
            goldMult = 1.5f,
            diamondReward = 14,
            hint = "High gold reserves \u2014 fortify both lanes so zero enemies pass through",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 44,
            title = "Lava Walkers",
            description = "Magma beasts immune to fire \u2014 rely on frost and arcane kinetic force",
            emoji = "\uD83E\uDD80",
            targetWave = 10,
            startingGold = 200,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.ICE, TowerType.TESLA, TowerType.BALLISTA),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.LIGHTNING),
            diamondReward = 13,
            hint = "Ice towers slow the magma beasts while Magic penetrates their molten shells",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.FLAME, "No Flame towers", "Bez wie\u017c ognia"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 45,
            title = "Molten Calamity",
            description = "Enraged Demon Prince assaults the caldera with seismic stomps",
            emoji = "\uD83D\uDE08",
            targetWave = 15,
            startingGold = 300,
            enemyHpMult = 1.25f,
            enemyDmgMult = 1.3f,
            diamondReward = 15,
            hint = "Watch for the 1.5s boss telegraph zone to move the hero out of danger",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Defeat the Demon Prince", "Pokonaj Ksi\u0119cia Demon\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater zabija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 46,
            title = "Ethereal Mist",
            description = "Spectral ghosts resist physical damage \u2014 harness the occult and electric",
            emoji = "\uD83C\uDF2B\uFE0F",
            targetWave = 9,
            startingGold = 210,
            allowedTowers = setOf(TowerType.MAGIC, TowerType.TESLA, TowerType.NECRO, TowerType.POISON),
            diamondReward = 13,
            hint = "Physical projectiles deal minimal damage; use Tesla and Magic arcs",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Clear Wave 9", "Przetrwaj Fal\u0119 9"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 47,
            title = "Duel in the Crypt",
            description = "Limited defenses \u2014 the Hero must stand as the primary bulwark",
            emoji = "\uD83D\uDDE1\uFE0F",
            targetWave = 7,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.HEALER),
            allowedPowers = emptySet(),
            diamondReward = 13,
            hint = "Keep the Hero near Healer auras to regenerate while cleaving through ghouls",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 7, null, "Survive all 7 waves", "Przetrwaj wszystkie 7 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 3, null, "Max 3 towers placed", "Maksymalnie 3 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.MIN_COMBO, 25, null, "Achieve 25x Kill Combo", "Osi\u0105gnij combo 25x")
        ),
        CampaignLevel(
            id = 48,
            title = "The Midas Curse",
            description = "Treasure flows like water, but greed attracts ravenous horrors",
            emoji = "\uD83D\uDCB0",
            targetWave = 10,
            startingGold = 150,
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            goldMult = 2.5f,
            diamondReward = 14,
            hint = "Spend your gold rapidly to upgrade towers before enemies overwhelm the perimeter",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 49,
            title = "Soul Harvest",
            description = "Command the Necromancer towers to raise a protective legion of bone",
            emoji = "\uD83E\uDDB4",
            targetWave = 12,
            startingGold = 240,
            allowedTowers = setOf(TowerType.NECRO, TowerType.MAGIC, TowerType.ICE, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 14,
            hint = "Resurrected skeletons block enemy pathing while Magic towers shred them",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 50,
            title = "Chrono Lich's Domain",
            description = "The ancient master of time bends reality and commands phantom thralls",
            emoji = "\u23F3",
            targetWave = 15,
            startingGold = 320,
            enemyHpMult = 1.3f,
            diamondReward = 16,
            hint = "Beware of time stuns; keep high DPS towers spread out to avoid synchronized shutdown",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Vanquish the Chrono Lich", "Pokonaj Chrono Licza"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich", "Bohater zabija Licza"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 75, null, "Base HP \u2265 75%", "Zdrowie bazy \u2265 75%")
        ),
        CampaignLevel(
            id = 51,
            title = "High Voltage",
            description = "Electrified ramparts \u2014 chain lightning across massive enemy swarms",
            emoji = "\u26A1",
            targetWave = 10,
            startingGold = 250,
            allowedTowers = setOf(TowerType.TESLA, TowerType.HEALER, TowerType.ARROW, TowerType.ICE),
            allowedPowers = setOf(PowerType.LIGHTNING),
            diamondReward = 14,
            hint = "Tesla coils chain to more targets when enemies are slowed by Ice",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Kill Combo", "Osi\u0105gnij combo 40x"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 52,
            title = "Four Pillars",
            description = "Sacred ground allows only 4 towers. Make every placement count",
            emoji = "\uD83C\uDFDB\uFE0F",
            targetWave = 11,
            startingGold = 350,
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            diamondReward = 15,
            hint = "Upgrade all 4 towers to Level 5 and specialize them for maximum coverage",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear all 11 waves", "Przetrwaj wszystkie 11 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 53,
            title = "Tempest Wing",
            description = "Thunderstorms rage as airborne Harpies evade ground artillery",
            emoji = "\uD83E\uDDA5",
            targetWave = 9,
            startingGold = 190,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.MAGIC, TowerType.TESLA),
            diamondReward = 14,
            hint = "Cannons cannot strike airborne targets; rely on Ballista and Tesla",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Survive all 9 waves", "Przetrwaj wszystkie 9 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.CANNON, "No Cannon towers", "Bez dzia\u0142"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 54,
            title = "Zero Arcana",
            description = "Anti-magic suppression field: pure mechanical defense only",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 220,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.BALLISTA, TowerType.HEALER),
            allowedPowers = emptySet(),
            diamondReward = 14,
            hint = "No spells available \u2014 use Ballistas to pierce heavy armor and Cannons for swarms",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 55,
            title = "The Storm Leviathan",
            description = "Colossal sea beast unleashes EMP waves that jam tower capacitors",
            emoji = "\uD83D\uDC09",
            targetWave = 15,
            startingGold = 350,
            enemyHpMult = 1.35f,
            diamondReward = 16,
            hint = "Prepare for EMP charges by moving your Hero into position to deal melee damage",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Slay the Storm Leviathan", "Zg\u0142ad\u017a Lewiatana Burz"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Boss", "Bohater zabija Bossa"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 56,
            title = "Shatterpoint",
            description = "Frozen enemies take 3x damage from blunt kinetic bombardment",
            emoji = "\uD83E\uDDCA",
            targetWave = 10,
            startingGold = 230,
            allowedTowers = setOf(TowerType.ICE, TowerType.CANNON, TowerType.BALLISTA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 14,
            hint = "Freeze incoming clusters, then crush them with heavy Cannon mortar rounds",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 45, null, "Achieve 45x Shatter Combo", "Osi\u0105gnij combo 45x"),
            objective3 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w")
        ),
        CampaignLevel(
            id = 57,
            title = "The Glacial Wall",
            description = "Massive frost giants: 300% HP, slow movement, unstoppable march",
            emoji = "\uD83C\uDFD4\uFE0F",
            targetWave = 8,
            startingGold = 280,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.POISON, TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = setOf(PowerType.FIREBALL),
            enemyHpMult = 3.0f,
            enemySpeedMult = 0.5f,
            diamondReward = 15,
            hint = "Stack Poison damage-over-time with high-velocity Ballista bolts",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Slay all Glacier Giants", "Pokonaj Olbrzymy Lodowe"),
            objective2 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 5, null, "Max 5 towers placed", "Maksymalnie 5 wie\u017c")
        ),
        CampaignLevel(
            id = 58,
            title = "Frostbite Paradox",
            description = "Bitter cold freezes your Ice towers \u2014 fight back with venom and fire",
            emoji = "\u2744\uFE0F",
            targetWave = 11,
            startingGold = 200,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON, TowerType.POISON, TowerType.FLAME, TowerType.TESLA),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            diamondReward = 15,
            hint = "Use Poison towers for crowd control when Ice is unavailable",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear Wave 11", "Przetrwaj Fal\u0119 11"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ICE, "No Ice towers", "Bez wie\u017c lodu"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 59,
            title = "Avalanche Run",
            description = "Relentless hordes cascade down the snowline every 10 seconds",
            emoji = "\uD83C\uDFC2",
            targetWave = 12,
            startingGold = 160,
            allowedTowers = setOf(TowerType.CANNON, TowerType.FLAME, TowerType.TESLA, TowerType.ICE),
            allowedPowers = setOf(PowerType.FIREBALL),
            spawnRateMult = 1.35f,
            diamondReward = 15,
            hint = "Lay down napalm carpets and cluster bombs at the primary bottleneck",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Survive all 12 waves", "Przetrwaj wszystkie 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 50, null, "Achieve 50x Avalanche Combo", "Osi\u0105gnij combo 50x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 60,
            title = "Frost Titan's Wrath",
            description = "The Frost Titan unleashes map-wide glacial quakes and ice shields",
            emoji = "\uD83D\uDC51",
            targetWave = 15,
            startingGold = 360,
            enemyHpMult = 1.4f,
            diamondReward = 17,
            hint = "Towers will be stunned at 25% boss HP; position Hero to absorb the seismic shock",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Shatter the Frost Titan", "Zg\u0142ad\u017a Tytana Mrozu"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Titan", "Bohater zabija Tytana"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 61,
            title = "Prismatic Shifters",
            description = "Enemies cycle damage immunities \u2014 mono-type defenses will fall",
            emoji = "\uD83D\uDD2E",
            targetWave = 10,
            startingGold = 250,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.FLAME, TowerType.TESLA, TowerType.BALLISTA),
            diamondReward = 15,
            hint = "Diversify your arsenal: blend physical, elemental, and energy damage",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 62,
            title = "Solar Eclipse",
            description = "Mystic celestial alignment: spell cooldowns cut in half!",
            emoji = "\u2600\uFE0F",
            targetWave = 10,
            startingGold = 180,
            allowedTowers = setOf(TowerType.ARROW, TowerType.HEALER, TowerType.MAGIC),
            diamondReward = 15,
            hint = "Cast Fireball and Freeze continuously while your Hero dashes with swiftness",
            mapType = MapType.DESERT,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.MIN_COMBO, 40, null, "Achieve 40x Combo", "Osi\u0105gnij combo 40x")
        ),
        CampaignLevel(
            id = 63,
            title = "Lone Champion",
            description = "Only 2 towers permitted. The Hero receives 2.5x empowered power",
            emoji = "\uD83E\uDD3A",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = setOf(TowerType.HEALER, TowerType.ICE, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Micro the empowered Hero to intercept leaders while Ice slows the pack",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive with Hero", "Przetrwaj Bohaterem"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 2, null, "Max 2 towers placed", "Maksymalnie 2 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 64,
            title = "Blood Moon Rampage",
            description = "Monsters in frenzy (+25% speed) under the sanguine orb. 2x spoils",
            emoji = "\uD83E\uDE78",
            targetWave = 12,
            startingGold = 200,
            enemyDmgMult = 1.25f,
            enemySpeedMult = 1.25f,
            goldMult = 2.0f,
            diamondReward = 16,
            hint = "High speed enemies mean chokepoints with Ice and Tesla are paramount",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Survive Blood Moon 12 waves", "Przetrwaj 12 fal Krwawego Ksi\u0119\u017cyca"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 65,
            title = "Void Phoenix Ascendant",
            description = "Astral guardian reincarnates upon death into a blazing stellar terror",
            emoji = "\uD83E\uDEB6",
            targetWave = 15,
            startingGold = 380,
            enemyHpMult = 1.4f,
            diamondReward = 18,
            hint = "Save burst abilities for the phoenix's second rebirth phase",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 15, null, "Banish the Void Phoenix", "Wygna\u0142 Feniksa Pustki"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Phoenix", "Bohater zabija Feniksa"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 66,
            title = "Twin Fractures",
            description = "Creeps assault from two separate paths simultaneously. Split defenses",
            emoji = "\u2694\uFE0F",
            targetWave = 12,
            startingGold = 300,
            diamondReward = 16,
            hint = "Distribute gold evenly between east and west corridors",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Hold both corridors 12 waves", "Utrzymaj oba korytarze 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 67,
            title = "The Purist",
            description = "Classic defense: Arrow and Cannon only. No spells, no upgrades",
            emoji = "\uD83C\uDFF9",
            targetWave = 14,
            startingGold = 160,
            allowedTowers = setOf(TowerType.ARROW, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            diamondReward = 17,
            hint = "Position Cannons to hit maximum intersections, and use Arrows for cleanup",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Clear all 14 waves", "Przetrwaj wszystkie 14 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 68,
            title = "The Iron Colosseum",
            description = "Armored behemoths and stone dreadnoughts withstand ordinary attacks",
            emoji = "\uD83E\uDD16",
            targetWave = 12,
            startingGold = 320,
            allowedTowers = setOf(TowerType.BALLISTA, TowerType.FLAME, TowerType.MAGIC, TowerType.POISON),
            allowedPowers = setOf(PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Armor Piercing Ballistas and Napalm melt dense metallic shells",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Kill Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 69,
            title = "The Boss Gauntlet",
            description = "Ten consecutive waves, ten relentless bosses. An unbroken trial",
            emoji = "\uD83D\uDC79",
            targetWave = 10,
            startingGold = 400,
            diamondReward = 20,
            hint = "A boss appears every wave \u2014 single target burst DPS is essential",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Survive all 10 Boss Waves", "Przetrwaj 10 Fal Boss\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 75, null, "Base HP \u2265 75%", "Zdrowie bazy \u2265 75%"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 8, null, "Max 8 towers placed", "Maksymalnie 8 wie\u017c")
        ),
        CampaignLevel(
            id = 70,
            title = "The Omni-Sovereign",
            description = "The ultimate cataclysm \u2014 the Omni-Sovereign commands all elements",
            emoji = "\uD83E\uDD34",
            targetWave = 20,
            startingGold = 450,
            enemyHpMult = 1.5f,
            enemyDmgMult = 1.4f,
            diamondReward = 25,
            hint = "Counters every element. Transition between kinetic, magic, and flame across 4 phases",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 20, null, "Vanquish the Omni-Sovereign", "Pokonaj Wszech-W\u0142adc\u0119"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero delivers finishing blow", "Bohater zadaje ostateczny cios"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 71,
            title = "Draugr's Awakening",
            description = "Frozen ancient skeletons freeze upon death, causing chain reactions",
            emoji = "\uD83E\uDEE6",
            targetWave = 11,
            startingGold = 220,
            allowedTowers = setOf(TowerType.ARROW, TowerType.ICE, TowerType.CANNON, TowerType.MAGIC),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Shatter frozen Draugr with Cannon shells to trigger shrapnel bursts",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 11, null, "Clear all 11 waves", "Przetrwaj wszystkie 11 fal"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 35, null, "Achieve 35x Shatter Combo", "Osi\u0105gnij combo 35x"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 72,
            title = "Soul-Frost Conduit",
            description = "Necromancer skeletons inherit chilling permafrost auras",
            emoji = "\uD83D\uDC7B",
            targetWave = 10,
            startingGold = 240,
            allowedTowers = setOf(TowerType.NECRO, TowerType.ICE, TowerType.MAGIC, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE),
            diamondReward = 16,
            hint = "Pair Healer towers with Necromancers to sustain freezing bone legions",
            mapType = MapType.VALLEY,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear Wave 10", "Przetrwaj Fal\u0119 10"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ARROW, "No Arrow towers", "Bez wie\u017c \u0142uczniczych"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 73,
            title = "The Frozen Phylactery",
            description = "Lich warlord protected by a frost ward \u2014 Hero must break the altar",
            emoji = "\uD83C\uDFFA",
            targetWave = 12,
            startingGold = 260,
            allowedTowers = setOf(TowerType.ARROW, TowerType.BALLISTA, TowerType.FLAME, TowerType.TESLA),
            allowedPowers = setOf(PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Move Hero into the fray to shatter the phylactery while towers provide cover",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Destroy Phylactery 12 waves", "Zniszcz Filakterium 12 fal"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich", "Bohater zabija Licza"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 85, null, "Base HP \u2265 85%", "Zdrowie bazy \u2265 85%")
        ),
        CampaignLevel(
            id = 74,
            title = "Black Ice Run",
            description = "Glacial speed rush (+60% velocity) \u2014 melt traction with napalm",
            emoji = "\u26F8\uFE0F",
            targetWave = 9,
            startingGold = 190,
            allowedTowers = setOf(TowerType.FLAME, TowerType.POISON, TowerType.TESLA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.LIGHTNING),
            enemyHpMult = 0.75f,
            enemySpeedMult = 1.6f,
            diamondReward = 16,
            hint = "Flame towers strip the ice speed boost and cause burning stalls",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 9, null, "Survive all 9 waves", "Przetrwaj wszystkie 9 fal"),
            objective2 = CampaignObjective(ObjectiveType.FORBIDDEN_TOWER, 0, TowerType.ICE, "No Ice towers", "Bez wie\u017c lodu"),
            objective3 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 5, null, "Max 5 towers placed", "Maksymalnie 5 wie\u017c")
        ),
        CampaignLevel(
            id = 75,
            title = "Frost-Bane Necromancer",
            description = "Blizzard sorcerer freezes defenses and raises frost ghouls",
            emoji = "\uD83E\uDDD9\u200D\u2642\uFE0F",
            targetWave = 14,
            startingGold = 320,
            diamondReward = 18,
            hint = "Ballistas with Armor Piercer bypass the ghouls' hardened frost plating",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 14, null, "Defeat Frost-Bane Necromancer", "Pokonaj Mro\u017anego Nekromant\u0119"),
            objective2 = CampaignObjective(ObjectiveType.NO_POWERS_USED, 0, null, "No spells used", "Bez u\u017cycia czar\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 76,
            title = "Corpse Shatter",
            description = "Frozen corpses ignite into secondary blasts from mortar impacts",
            emoji = "\uD83D\uDCA5",
            targetWave = 12,
            startingGold = 230,
            allowedTowers = setOf(TowerType.CANNON, TowerType.ICE, TowerType.BALLISTA, TowerType.HEALER),
            allowedPowers = setOf(PowerType.FREEZE, PowerType.FIREBALL),
            diamondReward = 17,
            hint = "Cluster enemies at corners where frozen bodies multiply mortar splash",
            mapType = MapType.CLASSIC,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 12, null, "Clear Wave 12", "Przetrwaj Fal\u0119 12"),
            objective2 = CampaignObjective(ObjectiveType.MIN_COMBO, 45, null, "Achieve 45x Shatter Combo", "Osi\u0105gnij combo 45x"),
            objective3 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c")
        ),
        CampaignLevel(
            id = 77,
            title = "The Whispering Mist",
            description = "Stealth phantoms stalk the swamp \u2014 illuminated only by aura and hero",
            emoji = "\uD83D\uDC7B",
            targetWave = 10,
            startingGold = 210,
            allowedTowers = setOf(TowerType.HEALER, TowerType.MAGIC, TowerType.TESLA, TowerType.ARROW),
            allowedPowers = setOf(PowerType.LIGHTNING),
            diamondReward = 17,
            hint = "Healer Sanctuary auras reveal hidden specters so turrets can target them",
            mapType = MapType.ENCHANTED,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 10, null, "Clear all 10 waves", "Przetrwaj wszystkie 10 fal"),
            objective2 = CampaignObjective(ObjectiveType.MAX_TOWERS_PLACED, 4, null, "Max 4 towers placed", "Maksymalnie 4 wie\u017ce"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 90, null, "Base HP \u2265 90%", "Zdrowie bazy \u2265 90%")
        ),
        CampaignLevel(
            id = 78,
            title = "Glacial Perma-Death",
            description = "Zero base repairs. Zero sell refunds. Pure irrevocable survival",
            emoji = "\u2620\uFE0F",
            targetWave = 8,
            startingGold = 300,
            allowedPowers = setOf(PowerType.FREEZE, PowerType.LIGHTNING),
            diamondReward = 18,
            hint = "Every hit to your base is permanent. Invest in layered control grids",
            mapType = MapType.SNOW,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 8, null, "Survive all 8 waves", "Przetrwaj wszystkie 8 fal"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Base (0 damage)", "Czysta baza (0 obra\u017ce\u0144)")
        ),
        CampaignLevel(
            id = 79,
            title = "Cryo-Cataclysm",
            description = "Volcano under freeze: odd waves fire-immune, even waves ice-immune",
            emoji = "\u267B\uFE0F",
            targetWave = 13,
            startingGold = 280,
            allowedTowers = setOf(TowerType.FLAME, TowerType.ICE, TowerType.CANNON, TowerType.MAGIC, TowerType.BALLISTA),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            diamondReward = 18,
            hint = "Build an alternating chessboard pattern of Flame and Ice towers",
            mapType = MapType.VOLCANO,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 13, null, "Clear 13 alternating waves", "Przetrwaj 13 fal naprzemiennych"),
            objective2 = CampaignObjective(ObjectiveType.NO_TOWERS_SOLD, 0, null, "No towers sold", "Bez sprzeda\u017cy wie\u017c"),
            objective3 = CampaignObjective(ObjectiveType.BASE_HP_ABOVE, 80, null, "Base HP \u2265 80%", "Zdrowie bazy \u2265 80%")
        ),
        CampaignLevel(
            id = 80,
            title = "The Glacial Lich-King",
            description = "Master of death and winter. 4-phase combat culminating in Absolute Zero",
            emoji = "\uD83E\uDDCA",
            targetWave = 20,
            startingGold = 420,
            enemyHpMult = 1.6f,
            enemyDmgMult = 1.5f,
            diamondReward = 30,
            hint = "Burst down the final phase with everything you have before Absolute Zero detonates",
            mapType = MapType.CROSSROADS,
            objective1 = CampaignObjective(ObjectiveType.SURVIVE_WAVES, 20, null, "Vanquish the Glacial Lich-King", "Zg\u0142ad\u017a Kr\u00f3la Licz\u00f3w"),
            objective2 = CampaignObjective(ObjectiveType.HERO_SLAYS_BOSS, 0, null, "Hero strikes down Lich-King", "Bohater zabija Kr\u00f3la Licz\u00f3w"),
            objective3 = CampaignObjective(ObjectiveType.PERFECT_BASE, 0, null, "Flawless Citadel (0 damage)", "Nienaruszona Cytadela (0 obra\u017ce\u0144)")
        )
    )
}