package com.example.myapp.game

data class CampaignLevel(
    val id: Int,
    val title: String,
    val description: String,
    val emoji: String,
    val targetWave: Int,
    val startingGold: Int = 50,
    val allowedTowers: Set<TowerType> = TowerType.entries.toSet(),
    val allowedPowers: Set<PowerType> = PowerType.entries.toSet(),
    val upgradesEnabled: Boolean = true,
    val enemyHpMult: Float = 1f,
    val enemyDmgMult: Float = 1f,
    val enemySpeedMult: Float = 1f,
    val goldMult: Float = 1f,
    val spawnRateMult: Float = 1f,
    val diamondReward: Int = 3,
    val hint: String = ""
)

object CampaignData {

    val levels = listOf(
        CampaignLevel(
            id = 1,
            title = "The Basics",
            description = "Place Arrow towers to stop the goblins!",
            emoji = "\uD83C\uDFF9",
            targetWave = 3,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.6f, enemyDmgMult = 0.5f, enemySpeedMult = 0.8f,
            goldMult = 1.5f,
            diamondReward = 2,
            hint = "Tap a tower button, then tap the field to place it"
        ),
        CampaignLevel(
            id = 2,
            title = "Magic Touch",
            description = "Magic towers deal more damage but cost more",
            emoji = "\uD83E\uDDE8",
            targetWave = 4,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.7f, enemyDmgMult = 0.6f, enemySpeedMult = 0.85f,
            goldMult = 1.3f,
            diamondReward = 2,
            hint = "Mix Arrow and Magic towers for best coverage"
        ),
        CampaignLevel(
            id = 3,
            title = "Heavy Artillery",
            description = "Cannons have splash potential — use them wisely",
            emoji = "\uD83D\uDCA3",
            targetWave = 5,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = false,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 3,
            hint = "Cannons are expensive but powerful"
        ),
        CampaignLevel(
            id = 4,
            title = "Upgrades!",
            description = "Learn to upgrade your towers and hero",
            emoji = "\u2B06\uFE0F",
            targetWave = 5,
            startingGold = 100,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f, enemySpeedMult = 0.9f,
            goldMult = 1.3f,
            diamondReward = 3,
            hint = "Tap a tower to select it, then press ⬆ TOWER to upgrade"
        ),
        CampaignLevel(
            id = 5,
            title = "Boss Battle",
            description = "Survive the first boss encounter!",
            emoji = "\u2620\uFE0F",
            targetWave = 5,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.7f, enemySpeedMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Every 5th wave is a boss wave — prepare your defenses!"
        ),
        CampaignLevel(
            id = 6,
            title = "Toxic Strategy",
            description = "Poison and Tesla towers join your arsenal",
            emoji = "\u2620\uFE0F",
            targetWave = 7,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.1f,
            diamondReward = 4,
            hint = "All 6 tower types are now available — try ICE to slow enemies!"
        ),
        CampaignLevel(
            id = 7,
            title = "Power Surge",
            description = "Learn to use powers in combat",
            emoji = "\uD83D\uDD25",
            targetWave = 7,
            startingGold = 120,
            allowedTowers = setOf(TowerType.ARROW, TowerType.MAGIC, TowerType.CANNON),
            allowedPowers = setOf(PowerType.FIREBALL, PowerType.FREEZE),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 4,
            hint = "Fireball damages all enemies. Freeze slows them down!"
        ),
        CampaignLevel(
            id = 8,
            title = "Full Arsenal",
            description = "All powers unlocked — master them all",
            emoji = "\u26A1",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1f, enemyDmgMult = 1f,
            goldMult = 1f,
            diamondReward = 5,
            hint = "Heal repairs your base, Lightning chains between enemies"
        ),
        CampaignLevel(
            id = 9,
            title = "The Horde",
            description = "Wave after wave of massive enemy numbers",
            emoji = "\uD83D\uDC80",
            targetWave = 10,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.9f,
            spawnRateMult = 1.5f, goldMult = 0.9f,
            diamondReward = 5,
            hint = "Lots of enemies incoming — build wide coverage"
        ),
        CampaignLevel(
            id = 10,
            title = "Tower Budget",
            description = "Gold is scarce — spend wisely!",
            emoji = "\uD83D\uDCB0",
            targetWave = 8,
            startingGold = 30,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 0.6f,
            diamondReward = 5,
            hint = "Every coin counts — upgrade instead of building new"
        ),
        CampaignLevel(
            id = 11,
            title = "Speed Demons",
            description = "Enemies move fast — freeze is your friend",
            emoji = "\uD83D\uDCA8",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.8f, enemyDmgMult = 0.8f,
            enemySpeedMult = 1.5f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Use Freeze power when enemies get close to the base"
        ),
        CampaignLevel(
            id = 12,
            title = "Iron Wall",
            description = "Enemies are tough — bring your best",
            emoji = "\uD83D\uDEE1\uFE0F",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.5f, enemyDmgMult = 1.3f,
            enemySpeedMult = 0.9f, goldMult = 1.2f,
            diamondReward = 6,
            hint = "Upgrade towers to deal with armored enemies"
        ),
        CampaignLevel(
            id = 13,
            title = "Boss Rush",
            description = "A boss every 3 waves — survive!",
            emoji = "\uD83D\uDC09",
            targetWave = 9,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Bosses come more frequently — keep upgrading"
        ),
        CampaignLevel(
            id = 14,
            title = "Arrows Only",
            description = "Only Arrow towers allowed — pure skill",
            emoji = "\uD83C\uDFAF",
            targetWave = 10,
            startingGold = 150,
            allowedTowers = setOf(TowerType.ARROW),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.8f,
            goldMult = 1.3f,
            diamondReward = 7,
            hint = "Upgrade your arrows and use powers to compensate"
        ),
        CampaignLevel(
            id = 15,
            title = "Night Raid",
            description = "Darkness falls — enemies are stronger at night",
            emoji = "\uD83C\uDF19",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            goldMult = 1.2f,
            diamondReward = 6,
            hint = "Night increases enemy HP by 20% and reduces tower range"
        ),
        CampaignLevel(
            id = 16,
            title = "Swarm Tactics",
            description = "Double enemies, half HP — overwhelm or be overwhelmed",
            emoji = "\uD83D\uDC1C",
            targetWave = 8,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 0.5f, enemyDmgMult = 0.7f,
            spawnRateMult = 2f, goldMult = 1.1f,
            diamondReward = 6,
            hint = "Many weak enemies — use splash damage towers!"
        ),
        CampaignLevel(
            id = 17,
            title = "No Powers",
            description = "Your powers are sealed — towers only!",
            emoji = "\uD83D\uDD12",
            targetWave = 8,
            startingGold = 120,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = emptySet(),
            upgradesEnabled = true,
            enemyHpMult = 0.9f, enemyDmgMult = 0.9f,
            goldMult = 1.2f,
            diamondReward = 7,
            hint = "No powers this time — rely on smart tower placement"
        ),
        CampaignLevel(
            id = 18,
            title = "Elite Forces",
            description = "Elite enemies appear every wave — be ready",
            emoji = "\uD83D\uDC51",
            targetWave = 10,
            startingGold = 100,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.1f, enemyDmgMult = 1f,
            goldMult = 1.3f,
            diamondReward = 8,
            hint = "Elite enemies have 3x HP and 2x gold — focus fire them"
        ),
        CampaignLevel(
            id = 19,
            title = "Gauntlet",
            description = "12 waves of escalating chaos",
            emoji = "\uD83D\uDD25",
            targetWave = 12,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.2f, enemyDmgMult = 1.1f,
            enemySpeedMult = 1.1f, goldMult = 1f,
            spawnRateMult = 1.3f,
            diamondReward = 9,
            hint = "This is the real test — manage gold and upgrades carefully"
        ),
        CampaignLevel(
            id = 20,
            title = "Final Stand",
            description = "The ultimate challenge — can you survive?",
            emoji = "\uD83C\uDFC6",
            targetWave = 15,
            startingGold = 80,
            allowedTowers = TowerType.entries.toSet(),
            allowedPowers = PowerType.entries.toSet(),
            upgradesEnabled = true,
            enemyHpMult = 1.4f, enemyDmgMult = 1.3f,
            enemySpeedMult = 1.1f, goldMult = 0.9f,
            spawnRateMult = 1.2f,
            diamondReward = 10,
            hint = "Use everything you've learned. Good luck!"
        )
    )
}
